// ==============================================================
// DATA.JS — Dane aplikacji (słówka, kategorie, pytania...)
// ==============================================================

const CATS=[
  {id:'all',label:'Wszystkie',color:'#d4af37'},
  {id:'cz1',label:'Czasowniki: Podstawy',color:'#22c55e'},
  {id:'cz2',label:'Czasowniki: Komunikacja',color:'#14b8a6'},
  {id:'cz3',label:'Czasowniki: Ruch ⚠',color:'#84cc16'},
  {id:'cz4',label:'Czasowniki: Umysł',color:'#06b6d4'},
  {id:'cz5',label:'Czasowniki: Dom',color:'#0ea5e9'},
  {id:'cz6',label:'Czasowniki: Emocje',color:'#ec4899'},
  {id:'dom1',label:'Dom: Pomieszczenia',color:'#3b82f6'},
  {id:'dom2',label:'Dom: Wyposażenie',color:'#6366f1'},
  {id:'nat1',label:'Natura: Niebo/Ziemia',color:'#10b981'},
  {id:'nat2',label:'Natura: Krajobrazy',color:'#059669'},
  {id:'zw1',label:'Zwierzęta: Domowe',color:'#f97316'},
  {id:'zw2',label:'Zwierzęta: Egzotyczne',color:'#f59e0b'},
  {id:'ani1',label:'Isekai: Bohaterowie',color:'#a855f7'},
  {id:'ani2',label:'Isekai: Wojownicy',color:'#9333ea'},
  {id:'ani3',label:'Isekai: Fantasy RPG',color:'#7e22ce'},
  {id:'extra',label:'Gramatyka',color:'#f59e0b'}
];
const D=[
  {cat:'cz1',e:'🍚',r:'taberu',m:'tabemasu',pl:'jeść',en:'to eat',ex:'Ringo wo tabemasu.',expl:'Jem jabłko.',ety:'czas. gr. 2 (-ru)',fun:'Jedna z pierwszych akcji adepta',part:'verb'},
  {cat:'cz1',e:'🥤',r:'nomu',m:'nomimasu',pl:'pić',en:'to drink',ex:'Mizu wo nomimasu.',expl:'Piję wodę.',ety:'czas. gr. 1',fun:'Nomiya = bar, gdzie się pije',part:'verb'},
  {cat:'cz1',e:'🚶',r:'iku',m:'ikimasu',pl:'iść',en:'to go',ex:'Gakkou ni ikimasu.',expl:'Idę do szkoły.',ety:'czas. gr. 1 nieregularny',fun:'Pułapka: forma -te = itte!',part:'verb'},
  {cat:'cz1',e:'🏃',r:'kuru',m:'kimasu',pl:'przychodzić',en:'to come',ex:'Tomodachi ga kimasu.',expl:'Przyjaciel przychodzi.',ety:'czas. nieregularny',fun:'Nie myl z "kiru" (ubierać)!',part:'verb'},
  {cat:'cz1',e:'🏠',r:'kaeru',m:'kaerimasu',pl:'wracać',en:'to return',ex:'Uchi ni kaerimasu.',expl:'Wracam do domu.',ety:'czas. gr. 1',fun:'Pułapka: "kaeru" = też żaba!',part:'verb'},
  {cat:'cz1',e:'💰',r:'kau',m:'kaimasu',pl:'kupować',en:'to buy',ex:'Hon wo kaimasu.',expl:'Kupuję książkę.',ety:'czas. gr. 1',fun:'Rdzeń handlu',part:'verb'},
  {cat:'cz1',e:'💡',r:'wakaru',m:'wakarimasu',pl:'rozumieć',en:'to understand',ex:'Wakarimashita!',expl:'Zrozumiałem!',ety:'czas. gr. 1',fun:'Frazę znasz z każdego anime',part:'verb'},
  {cat:'cz1',e:'🧠',r:'shiru',m:'shitte imasu',pl:'wiedzieć',en:'to know',ex:'Shitte imasu.',expl:'Wiem.',ety:'czas. gr. 1',fun:'Uwaga: w teraźniejszym używa się shitte imasu',part:'verb'},
  {cat:'cz1',e:'❤️',r:'suki da',m:'suki desu',pl:'lubić',en:'to like',ex:'Anime ga suki desu.',expl:'Lubię anime.',ety:'przymiotnik na',fun:'Suki desu = też "kocham"',part:'verb'},
  {cat:'cz1',e:'✨',r:'hoshii',m:'hoshii desu',pl:'chcieć',en:'to want',ex:'Neko ga hoshii.',expl:'Chcę kota.',ety:'przymiotnik i',fun:'Uwaga: hoshi = gwiazda, hoshii = chcieć!',part:'verb'},
  {cat:'cz2',e:'💬',r:'hanasu',m:'hanashimasu',pl:'mówić / rozmawiać',en:'to speak',ex:'Nihongo wo hanashimasu.',expl:'Mówię po japońsku.',ety:'czas. gr. 1',fun:'Hanashi = rozmowa',part:'verb'},
  {cat:'cz2',e:'👂',r:'kiku',m:'kikimasu',pl:'słuchać / pytać',en:'to listen / ask',ex:'Ongaku wo kikimasu.',expl:'Słucham muzyki.',ety:'czas. gr. 1',fun:'Dwuznaczne - kontekst decyduje',part:'verb'},
  {cat:'cz2',e:'👀',r:'miru',m:'mimasu',pl:'oglądać / patrzeć',en:'to watch / see',ex:'Anime wo mimasu.',expl:'Oglądam anime.',ety:'czas. gr. 2',fun:'Podstawowy zmysł',part:'verb'},
  {cat:'cz2',e:'📖',r:'yomu',m:'yomimasu',pl:'czytać',en:'to read',ex:'Hon wo yomimasu.',expl:'Czytam książkę.',ety:'czas. gr. 1',fun:'Rdzeń "recytowania"',part:'verb'},
  {cat:'cz2',e:'✍️',r:'kaku',m:'kakimasu',pl:'pisać',en:'to write',ex:'Tegami wo kakimasu.',expl:'Piszę list.',ety:'czas. gr. 1',fun:'Też znaczy "rysować"',part:'verb'},
  {cat:'cz2',e:'💼',r:'hataraku',m:'hatarakimasu',pl:'pracować',en:'to work',ex:'Kaisha de hatarakimasu.',expl:'Pracuję w firmie.',ety:'czas. gr. 1',fun:'Hatarakimono = pracoholik',part:'verb'},
  {cat:'cz2',e:'🏡',r:'sumu',m:'sunde imasu',pl:'mieszkać',en:'to live (reside)',ex:'Tokyo ni sunde imasu.',expl:'Mieszkam w Tokio.',ety:'czas. gr. 1',fun:'W teraźniejszym: sunde imasu',part:'verb'},
  {cat:'cz2',e:'😴',r:'neru',m:'nemasu',pl:'spać',en:'to sleep',ex:'Hayaku nemasu.',expl:'Wcześnie śpię.',ety:'czas. gr. 2',fun:'Nemui = senny',part:'verb'},
  {cat:'cz2',e:'☀️',r:'okiru',m:'okimasu',pl:'budzić się',en:'to wake up',ex:'Roku-ji ni okimasu.',expl:'Wstaję o szóstej.',ety:'czas. gr. 2',fun:'Pułapka: różne od "okoru" - gniewać się',part:'verb'},
  {cat:'cz2',e:'⚡',r:'suru',m:'shimasu',pl:'robić / działać',en:'to do',ex:'Benkyou wo shimasu.',expl:'Uczę się.',ety:'czas. nieregularny',fun:'Łączy się z mnóstwem rzeczowników',part:'verb'},
  {cat:'cz3',e:'⏳',r:'matsu',m:'machimasu',pl:'czekać',en:'to wait',ex:'Tomodachi wo machimasu.',expl:'Czekam na przyjaciela.',ety:'czas. gr. 1',fun:'Pułapka: t→ch w -masu!',part:'verb'},
  {cat:'cz3',e:'🧍',r:'tatsu',m:'tachimasu',pl:'stać',en:'to stand',ex:'Koko ni tachimasu.',expl:'Stoję tutaj.',ety:'czas. gr. 1',fun:'Podobna pułapka t→ch',part:'verb'},
  {cat:'cz3',e:'💺',r:'suwaru',m:'suwarimasu',pl:'siedzieć',en:'to sit',ex:'Isu ni suwarimasu.',expl:'Siadam na krześle.',ety:'czas. gr. 1',fun:'Częsta pomyłka w testach',part:'verb'},
  {cat:'cz3',e:'🏃‍♂️',r:'hashiru',m:'hashirimasu',pl:'biec',en:'to run',ex:'Mori wo hashirimasu.',expl:'Biegnę przez las.',ety:'czas. gr. 1 (wyjątek!)',fun:'Wygląda jak gr. 2 ale jest gr. 1',part:'verb'},
  {cat:'cz3',e:'🚶‍♀️',r:'aruku',m:'arukimasu',pl:'chodzić / spacerować',en:'to walk',ex:'Kouen wo arukimasu.',expl:'Spaceruję w parku.',ety:'czas. gr. 1',fun:'Rdzeń "kroczenia"',part:'verb'},
  {cat:'cz3',e:'🎁',r:'ageru',m:'agemasu',pl:'dawać',en:'to give',ex:'Hana wo agemasu.',expl:'Daję kwiaty.',ety:'czas. gr. 2',fun:'Para z "morau"!',part:'verb'},
  {cat:'cz3',e:'🙏',r:'morau',m:'moraimasu',pl:'dostawać / otrzymywać',en:'to receive',ex:'Purezento wo moraimasu.',expl:'Dostaję prezent.',ety:'czas. gr. 1',fun:'Para przeciwieństw z "ageru"',part:'verb'},
  {cat:'cz3',e:'🔍',r:'sagasu',m:'sagashimasu',pl:'szukać',en:'to search',ex:'Kagi wo sagashimasu.',expl:'Szukam klucza.',ety:'czas. gr. 1',fun:'Pułapka: s→sh w -masu!',part:'verb'},
  {cat:'cz3',e:'🌅',r:'hajimeru',m:'hajimemasu',pl:'zaczynać',en:'to begin',ex:'Ressun wo hajimemasu.',expl:'Zaczynam lekcję.',ety:'czas. gr. 2',fun:'Hajime! = Start!',part:'verb'},
  {cat:'cz3',e:'🌇',r:'owaru',m:'owarimasu',pl:'kończyć',en:'to end',ex:'Shigoto ga owarimasu.',expl:'Praca się kończy.',ety:'czas. gr. 1',fun:'"Owari" - napis końca anime',part:'verb'},
  {cat:'cz4',e:'💭',r:'omou',m:'omoimasu',pl:'myśleć',en:'to think',ex:'Sou omoimasu.',expl:'Tak myślę.',ety:'czas. gr. 1',fun:'Subiektywna opinia',part:'verb'},
  {cat:'cz4',e:'🧠',r:'oboeru',m:'oboemasu',pl:'pamiętać',en:'to remember',ex:'Kanji wo oboemasu.',expl:'Zapamiętuję kanji.',ety:'czas. gr. 2',fun:'Rdzeń pamięci',part:'verb'},
  {cat:'cz4',e:'🫗',r:'wasureru',m:'wasuremasu',pl:'zapominać',en:'to forget',ex:'Namae wo wasuremashita.',expl:'Zapomniałem imienia.',ety:'czas. gr. 2',fun:'Para z "oboeru"',part:'verb'},
  {cat:'cz4',e:'💬',r:'kotaeru',m:'kotaemasu',pl:'odpowiadać',en:'to answer',ex:'Shitsumon ni kotaemasu.',expl:'Odpowiadam na pytanie.',ety:'czas. gr. 2',fun:'Kotae = odpowiedź',part:'verb'},
  {cat:'cz4',e:'🤝',r:'tasukeru',m:'tasukemasu',pl:'pomagać',en:'to help',ex:'Tomodachi wo tasukemasu.',expl:'Pomagam przyjacielowi.',ety:'czas. gr. 2',fun:'Tasukete! = Pomocy!',part:'verb'},
  {cat:'cz4',e:'👋',r:'au',m:'aimasu',pl:'spotykać',en:'to meet',ex:'Sensei ni aimasu.',expl:'Spotykam nauczyciela.',ety:'czas. gr. 1',fun:'Używa partykuły NI!',part:'verb'},
  {cat:'cz4',e:'📢',r:'setsumei suru',m:'setsumei shimasu',pl:'wyjaśniać',en:'to explain',ex:'Mondai wo setsumei shimasu.',expl:'Wyjaśniam problem.',ety:'rzecz. + suru',fun:'Schemat: setsumei (wyj.) + suru',part:'verb'},
  {cat:'cz4',e:'😔',r:'ayamaru',m:'ayamarimasu',pl:'przepraszać',en:'to apologize',ex:'Ayamarimashita.',expl:'Przeprosiłem.',ety:'czas. gr. 1',fun:'Formalne przepraszanie',part:'verb'},
  {cat:'cz4',e:'🙏',r:'kansha suru',m:'kansha shimasu',pl:'dziękować',en:'to thank',ex:'Kansha shimasu.',expl:'Dziękuję (oficjalnie).',ety:'rzecz. + suru',fun:'Bardzo formalne',part:'verb'},
  {cat:'cz4',e:'👍',r:'sansei suru',m:'sansei shimasu',pl:'zgadzać się',en:'to agree',ex:'Iken ni sansei shimasu.',expl:'Zgadzam się z opinią.',ety:'rzecz. + suru',fun:'W debatach',part:'verb'},
  {cat:'cz4',e:'😠',r:'kenka suru',m:'kenka shimasu',pl:'kłócić się',en:'to quarrel',ex:'Tomodachi to kenka shita.',expl:'Pokłóciłem się z przyjacielem.',ety:'rzecz. + suru',fun:'Używa TO (z kimś)',part:'verb'},
  {cat:'cz4',e:'❓',r:'shitsumon suru',m:'shitsumon shimasu',pl:'zadawać pytanie',en:'to question',ex:'Sensei ni shitsumon shimasu.',expl:'Pytam nauczyciela.',ety:'rzecz. + suru',fun:'Grzeczniejsze od "kiku"',part:'verb'},
  {cat:'cz4',e:'🧘',r:'shinjiru',m:'shinjimasu',pl:'wierzyć',en:'to believe',ex:'Unmei wo shinjimasu.',expl:'Wierzę w przeznaczenie.',ety:'czas. gr. 2',fun:'Częste w anime finałach',part:'verb'},
  {cat:'cz5',e:'🚪',r:'akeru',m:'akemasu',pl:'otwierać',en:'to open',ex:'Doa wo akemasu.',expl:'Otwieram drzwi.',ety:'czas. gr. 2',fun:'Nie myl z ageru!',part:'verb'},
  {cat:'cz5',e:'🔒',r:'shimeru',m:'shimemasu',pl:'zamykać',en:'to close',ex:'Mado wo shimemasu.',expl:'Zamykam okno.',ety:'czas. gr. 2',fun:'Para z "akeru"',part:'verb'},
  {cat:'cz5',e:'🚶‍♂️',r:'hairu',m:'hairimasu',pl:'wchodzić',en:'to enter',ex:'Heya ni hairimasu.',expl:'Wchodzę do pokoju.',ety:'czas. gr. 1 (wyjątek!)',fun:'Wygląda jak gr. 2 ale jest gr. 1',part:'verb'},
  {cat:'cz5',e:'🚪',r:'deru',m:'demasu',pl:'wychodzić',en:'to exit',ex:'Uchi wo demasu.',expl:'Wychodzę z domu.',ety:'czas. gr. 2',fun:'Para z "hairu"',part:'verb'},
  {cat:'cz5',e:'🔧',r:'tsukau',m:'tsukaimasu',pl:'używać',en:'to use',ex:'Pen wo tsukaimasu.',expl:'Używam długopisu.',ety:'czas. gr. 1',fun:'Uniwersalne',part:'verb'},
  {cat:'cz5',e:'🛠️',r:'tsukuru',m:'tsukurimasu',pl:'tworzyć / robić',en:'to make',ex:'Ryouri wo tsukurimasu.',expl:'Przygotowuję posiłek.',ety:'czas. gr. 1',fun:'Rzemiosło',part:'verb'},
  {cat:'cz5',e:'💸',r:'uru',m:'urimasu',pl:'sprzedawać',en:'to sell',ex:'Kuruma wo urimasu.',expl:'Sprzedaję samochód.',ety:'czas. gr. 1',fun:'Para z "kau"',part:'verb'},
  {cat:'cz5',e:'👘',r:'kiru',m:'kimasu',pl:'ubierać / nosić',en:'to wear',ex:'Kimono wo kimasu.',expl:'Noszę kimono.',ety:'czas. gr. 2',fun:'Nie myl z "kuru" (przyjść)!',part:'verb'},
  {cat:'cz5',e:'🧼',r:'arau',m:'araimasu',pl:'myć',en:'to wash',ex:'Te wo araimasu.',expl:'Myję ręce.',ety:'czas. gr. 1',fun:'Podstawowa czynność',part:'verb'},
  {cat:'cz5',e:'🍳',r:'ryouri suru',m:'ryouri shimasu',pl:'gotować',en:'to cook',ex:'Ryouri wo shimasu.',expl:'Gotuję.',ety:'rzecz. + suru',fun:'Ryouri = kuchnia/danie',part:'verb'},
  {cat:'cz6',e:'😂',r:'warau',m:'waraimasu',pl:'śmiać się',en:'to laugh',ex:'Minna ga warau.',expl:'Wszyscy się śmieją.',ety:'czas. gr. 1',fun:'Warai = śmiech',part:'verb'},
  {cat:'cz6',e:'😭',r:'naku',m:'nakimasu',pl:'płakać',en:'to cry',ex:'Akachan ga naku.',expl:'Dziecko płacze.',ety:'czas. gr. 1',fun:'Z pasją i dramatem',part:'verb'},
  {cat:'cz6',e:'🎤',r:'utau',m:'utaimasu',pl:'śpiewać',en:'to sing',ex:'Uta wo utaimasu.',expl:'Śpiewam piosenkę.',ety:'czas. gr. 1',fun:'Uta = piosenka',part:'verb'},
  {cat:'cz6',e:'💃',r:'odoru',m:'odorimasu',pl:'tańczyć',en:'to dance',ex:'Odori wo odorimasu.',expl:'Tańczę taniec.',ety:'czas. gr. 1',fun:'Klasyczne w festiwalach',part:'verb'},
  {cat:'cz6',e:'🎮',r:'asobu',m:'asobimasu',pl:'bawić się / grać',en:'to play',ex:'Tomodachi to asobimasu.',expl:'Bawię się z przyjaciółmi.',ety:'czas. gr. 1',fun:'Używa TO',part:'verb'},
  {cat:'cz6',e:'📚',r:'benkyou suru',m:'benkyou shimasu',pl:'uczyć się',en:'to study',ex:'Nihongo wo benkyou shimasu.',expl:'Uczę się japońskiego.',ety:'rzecz. + suru',fun:'Twój codzienny rytuał!',part:'verb'},
  {cat:'cz6',e:'👨‍🏫',r:'oshieru',m:'oshiemasu',pl:'uczyć kogoś',en:'to teach',ex:'Kanji wo oshiemasu.',expl:'Uczę kanji.',ety:'czas. gr. 2',fun:'Para z "benkyou suru"',part:'verb'},
  {cat:'dom1',e:'🏠',r:'uchi',m:'—',pl:'dom / mieszkanie',en:'home',ex:'Uchi ni kaerimasu.',expl:'Wracam do domu.',ety:'uchi = wewnątrz',fun:'Swojski dom',part:'noun'},
  {cat:'dom1',e:'🏢',r:'apaato',m:'—',pl:'mieszkanie (apartament)',en:'apartment',ex:'Apaato ni sumu.',expl:'Mieszkam w apartamencie.',ety:'z angielskiego',fun:'Zachodnie zapożyczenie',part:'noun'},
  {cat:'dom1',e:'🛋️',r:'heya',m:'—',pl:'pokój',en:'room',ex:'Heya ga kirei desu.',expl:'Pokój jest czysty.',ety:'pomieszczenie',fun:'Podstawowe',part:'noun'},
  {cat:'dom1',e:'🍳',r:'daidokoro',m:'—',pl:'kuchnia',en:'kitchen',ex:'Daidokoro de ryouri.',expl:'W kuchni gotuję.',ety:'"wielkie miejsce"',fun:'Serce japońskiego domu',part:'noun'},
  {cat:'dom1',e:'🛁',r:'ofuro',m:'—',pl:'łazienka / kąpiel',en:'bath',ex:'Ofuro ni hairimasu.',expl:'Wchodzę do kąpieli.',ety:'o + furo (kąpiel)',fun:'Japończycy się w niej namaczają!',part:'noun'},
  {cat:'dom1',e:'🚽',r:'toire',m:'—',pl:'toaleta',en:'toilet',ex:'Toire wa doko desu ka?',expl:'Gdzie jest toaleta?',ety:'z angielskiego',fun:'Często oddzielona od łazienki',part:'noun'},
  {cat:'dom1',e:'🛏️',r:'shinshitsu',m:'—',pl:'sypialnia',en:'bedroom',ex:'Shinshitsu de nemasu.',expl:'Śpię w sypialni.',ety:'"miejsce spania"',fun:'Formalne słowo',part:'noun'},
  {cat:'dom1',e:'🛋️',r:'ima',m:'—',pl:'salon',en:'living room',ex:'Ima de terebi wo mimasu.',expl:'W salonie oglądam TV.',ety:'"teraz/obecny"',fun:'Żywe centrum domu',part:'noun'},
  {cat:'dom1',e:'🌸',r:'niwa',m:'—',pl:'ogród',en:'garden',ex:'Niwa ni hana ga saku.',expl:'W ogrodzie kwitną kwiaty.',ety:'pradawne',fun:'Japońskie ogrody są sztuką',part:'noun'},
  {cat:'dom1',e:'🪟',r:'mado',m:'—',pl:'okno',en:'window',ex:'Mado wo akemasu.',expl:'Otwieram okno.',ety:'"oko domu"',fun:'Tradycyjne - z papieru',part:'noun'},
  {cat:'dom1',e:'🚪',r:'doa',m:'—',pl:'drzwi',en:'door',ex:'Doa wo shimemasu.',expl:'Zamykam drzwi.',ety:'z angielskiego',fun:'Nowoczesne - japońskie = fusuma',part:'noun'},
  {cat:'dom1',e:'⬜',r:'yuka',m:'—',pl:'podłoga',en:'floor',ex:'Yuka ni suwaru.',expl:'Siedzę na podłodze.',ety:'tradycja',fun:'Tatami - mata słomiana',part:'noun'},
  {cat:'dom1',e:'⬜',r:'tenjou',m:'—',pl:'sufit',en:'ceiling',ex:'Tenjou ga takai desu.',expl:'Sufit jest wysoki.',ety:'"niebo pokoju"',fun:'Poetyckie',part:'noun'},
  {cat:'dom1',e:'🧱',r:'kabe',m:'—',pl:'ściana',en:'wall',ex:'Kabe ni e wo kakeru.',expl:'Wieszam obraz na ścianie.',ety:'granica',fun:'Podstawowe',part:'noun'},
  {cat:'dom1',e:'🪜',r:'kaidan',m:'—',pl:'schody',en:'stairs',ex:'Kaidan wo noboru.',expl:'Wchodzę po schodach.',ety:'stopnie',fun:'W pałacach wiele stopni',part:'noun'},
  {cat:'dom1',e:'🪑',r:'teburu',m:'—',pl:'stół',en:'table',ex:'Teburu ni shokuji.',expl:'Posiłek na stole.',ety:'z angielskiego',fun:'Zachodnie zapożyczenie',part:'noun'},
  {cat:'dom1',e:'🪑',r:'isu',m:'—',pl:'krzesło',en:'chair',ex:'Isu ni suwaru.',expl:'Siadam na krześle.',ety:'tradycja',fun:'Podstawowe',part:'noun'},
  {cat:'dom1',e:'🛏️',r:'beddo',m:'—',pl:'łóżko',en:'bed',ex:'Beddo de neru.',expl:'Śpię w łóżku.',ety:'z angielskiego',fun:'Futon = tradycyjny',part:'noun'},
  {cat:'dom1',e:'🗄️',r:'tansu',m:'—',pl:'szafa',en:'wardrobe',ex:'Tansu ni fuku.',expl:'Ubrania w szafie.',ety:'tradycja',fun:'Tradycyjny japoński mebel',part:'noun'},
  {cat:'dom1',e:'💡',r:'ranpu',m:'—',pl:'lampa',en:'lamp',ex:'Ranpu wo tsukeru.',expl:'Zapalam lampę.',ety:'z angielskiego',fun:'Oświetlenie',part:'noun'},
  {cat:'dom2',e:'🚗',r:'gareeji',m:'—',pl:'garaż',en:'garage',ex:'Kuruma wa gareeji ni.',expl:'Samochód w garażu.',ety:'z angielskiego',fun:'Nowoczesne',part:'noun'},
  {cat:'dom2',e:'🕳️',r:'chika',m:'—',pl:'piwnica',en:'basement',ex:'Chika ga kurai.',expl:'Piwnica jest ciemna.',ety:'"pod-ziemią"',fun:'Rzadko w Japonii',part:'noun'},
  {cat:'dom2',e:'🏚️',r:'yaneura',m:'—',pl:'strych',en:'attic',ex:'Yaneura ni hako.',expl:'Pudełka na strychu.',ety:'"pod dachem"',fun:'Miejsce sekretów',part:'noun'},
  {cat:'dom2',e:'🚶',r:'rouka',m:'—',pl:'korytarz',en:'hallway',ex:'Rouka wo aruku.',expl:'Idę korytarzem.',ety:'"przechodni"',fun:'Łączy pokoje',part:'noun'},
  {cat:'dom2',e:'👘',r:'genkan',m:'—',pl:'wejście / przedsionek',en:'entrance hall',ex:'Genkan de kutsu wo nugu.',expl:'Przy wejściu zdejmuję buty.',ety:'"brama"',fun:'Kulturowo WAŻNE - tu zdejmujesz buty!',part:'noun'},
  {cat:'dom2',e:'🏠',r:'barukoni',m:'—',pl:'balkon',en:'balcony',ex:'Barukoni de yasumu.',expl:'Odpoczywam na balkonie.',ety:'z angielskiego',fun:'Suszenie prania',part:'noun'},
  {cat:'dom2',e:'🌿',r:'terasu',m:'—',pl:'taras',en:'terrace',ex:'Terasu de kafe.',expl:'Kawa na tarasie.',ety:'z angielskiego',fun:'Zachodnie',part:'noun'},
  {cat:'dom2',e:'🪵',r:'hei',m:'—',pl:'płot',en:'fence',ex:'Hei ga takai.',expl:'Płot jest wysoki.',ety:'granica',fun:'Chroni prywatność',part:'noun'},
  {cat:'dom2',e:'🚪',r:'mon',m:'—',pl:'brama',en:'gate',ex:'Mon wo kuguru.',expl:'Przechodzę przez bramę.',ety:'tradycja',fun:'Ważne: mon świątynne = torii',part:'noun'},
  {cat:'dom2',e:'🔑',r:'kagi',m:'—',pl:'klucz',en:'key',ex:'Kagi wo sagasu.',expl:'Szukam klucza.',ety:'"zamek"',fun:'Oznacza też "zamek"',part:'noun'},
  {cat:'dom2',e:'🔒',r:'jou',m:'—',pl:'zamek (do drzwi)',en:'lock',ex:'Jou wo kakeru.',expl:'Zamykam zamek.',ety:'technika',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'dom2',e:'🗄️',r:'tana',m:'—',pl:'półka',en:'shelf',ex:'Tana ni hon ga.',expl:'Książki na półce.',ety:'drewno',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'dom2',e:'🪞',r:'kagami',m:'—',pl:'lustro',en:'mirror',ex:'Kagami wo miru.',expl:'Patrzę w lustro.',ety:'błyszczące szkło',fun:'W bajkach - magiczne',part:'noun'},
  {cat:'dom2',e:'🧶',r:'jutan',m:'—',pl:'dywan',en:'carpet',ex:'Jutan ga atatakai.',expl:'Dywan jest ciepły.',ety:'z perskiego',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'dom2',e:'🎭',r:'kaaten',m:'—',pl:'zasłona',en:'curtain',ex:'Kaaten wo hiku.',expl:'Zasuwam zasłonę.',ety:'z angielskiego',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'dom2',e:'🛌',r:'makura',m:'—',pl:'poduszka',en:'pillow',ex:'Makura ga yawarakai.',expl:'Poduszka jest miękka.',ety:'tradycja',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'dom2',e:'🛌',r:'moufu',m:'—',pl:'kołdra',en:'blanket',ex:'Moufu wo kakeru.',expl:'Przykrywam się kołdrą.',ety:'"wełna pokrycia"',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'dom2',e:'🛁',r:'batsu',m:'—',pl:'wanna',en:'bathtub',ex:'Batsu ni hairu.',expl:'Wchodzę do wanny.',ety:'z angielskiego bath',fun:'Słabe słowo - ucz się!',part:'noun'},
  {cat:'nat1',e:'☀️',r:'taiyou',m:'—',pl:'słońce',en:'sun',ex:'Taiyou ga deru.',expl:'Słońce wschodzi.',ety:'bogini Amaterasu',fun:'Najważniejsze bóstwo shinto',part:'noun'},
  {cat:'nat1',e:'🌙',r:'tsuki',m:'—',pl:'księżyc',en:'moon',ex:'Tsuki ga kirei.',expl:'Księżyc jest piękny.',ety:'tradycja',fun:'Tsukimi - święto oglądania księżyca',part:'noun'},
  {cat:'nat1',e:'⭐',r:'hoshi',m:'—',pl:'gwiazda',en:'star',ex:'Hoshi ga hikaru.',expl:'Gwiazdy błyszczą.',ety:'"światło"',fun:'Uwaga: hoshi vs hoshii!',part:'noun'},
  {cat:'nat1',e:'🌌',r:'sora',m:'—',pl:'niebo',en:'sky',ex:'Sora wa aoi.',expl:'Niebo jest niebieskie.',ety:'przestrzeń',fun:'W isekai: cel tęsknoty',part:'noun'},
  {cat:'nat1',e:'☁️',r:'kumo',m:'—',pl:'chmura',en:'cloud',ex:'Kumo ga nagare.',expl:'Chmury płyną.',ety:'para wodna',fun:'Uwaga: kumo = też pająk!',part:'noun'},
  {cat:'nat1',e:'🌧️',r:'ame',m:'—',pl:'deszcz',en:'rain',ex:'Ame ga furu.',expl:'Pada deszcz.',ety:'kropla',fun:'Częste w Japonii',part:'noun'},
  {cat:'nat1',e:'❄️',r:'yuki',m:'—',pl:'śnieg',en:'snow',ex:'Yuki ga tsumoru.',expl:'Śnieg się zbiera.',ety:'zima',fun:'Yukimatsuri - festiwal śniegu',part:'noun'},
  {cat:'nat1',e:'💨',r:'kaze',m:'—',pl:'wiatr',en:'wind / cold',ex:'Kaze ga fuku.',expl:'Wieje wiatr.',ety:'ruch powietrza',fun:'Uwaga: "kaze" też = przeziębienie!',part:'noun'},
  {cat:'nat1',e:'⛈️',r:'arashi',m:'—',pl:'burza',en:'storm',ex:'Arashi ga kuru.',expl:'Nadchodzi burza.',ety:'gniew natury',fun:'Dramatyczne',part:'noun'},
  {cat:'nat1',e:'🌈',r:'niji',m:'—',pl:'tęcza',en:'rainbow',ex:'Ame no ato ni niji.',expl:'Po deszczu tęcza.',ety:'7 kolorów',fun:'Zjawisko magiczne',part:'noun'},
  {cat:'nat1',e:'🌊',r:'umi',m:'—',pl:'morze / ocean',en:'sea',ex:'Umi wo miru.',expl:'Patrzę na morze.',ety:'wielka woda',fun:'Japonia - wyspiarski kraj',part:'noun'},
  {cat:'nat1',e:'🏞️',r:'kawa',m:'—',pl:'rzeka',en:'river',ex:'Kawa ga nagareru.',expl:'Rzeka płynie.',ety:'płynąca woda',fun:'Shinto kami = duchy rzek',part:'noun'},
  {cat:'nat1',e:'⛰️',r:'yama',m:'—',pl:'góra',en:'mountain',ex:'Yama ni noboru.',expl:'Wspinam się na górę.',ety:'wzniesienie',fun:'Fuji-san - święta góra',part:'noun'},
  {cat:'nat1',e:'🌲',r:'mori',m:'—',pl:'las',en:'forest',ex:'Mori de aruku.',expl:'Spaceruję w lesie.',ety:'gęsty bór',fun:'W lesie mieszkają yokai',part:'noun'},
  {cat:'nat1',e:'🌳',r:'ki',m:'—',pl:'drzewo',en:'tree',ex:'Ki no shita de.',expl:'Pod drzewem.',ety:'roślina',fun:'Sakura najczęstsze',part:'noun'},
  {cat:'nat1',e:'🌸',r:'hana',m:'—',pl:'kwiat',en:'flower',ex:'Hana ga saku.',expl:'Kwiaty kwitną.',ety:'roślina',fun:'Hanami = święto oglądania kwiatów',part:'noun'},
  {cat:'nat1',e:'🌱',r:'kusa',m:'—',pl:'trawa',en:'grass',ex:'Kusa ga aoi.',expl:'Trawa jest zielona.',ety:'rośliny',fun:'Pospolite',part:'noun'},
  {cat:'nat1',e:'🪨',r:'ishi',m:'—',pl:'kamień',en:'stone',ex:'Ishi wo nageru.',expl:'Rzucam kamień.',ety:'twardy',fun:'Podstawowe',part:'noun'},
  {cat:'nat1',e:'🌍',r:'tsuchi',m:'—',pl:'ziemia / grunt',en:'earth / soil',ex:'Tsuchi ga atatakai.',expl:'Ziemia jest ciepła.',ety:'element',fun:'Podstawowy żywioł',part:'noun'},
  {cat:'nat1',e:'🔥',r:'hi',m:'—',pl:'ogień / dzień',en:'fire / day',ex:'Hi ga atsui.',expl:'Ogień jest gorący.',ety:'element',fun:'Uwaga: hi = też dzień!',part:'noun'},
  {cat:'nat2',e:'🌊',r:'mizuumi',m:'—',pl:'jezioro',en:'lake',ex:'Mizuumi ga shizuka.',expl:'Jezioro jest spokojne.',ety:'"wielka woda"',fun:'Spokojne',part:'noun'},
  {cat:'nat2',e:'💧',r:'ike',m:'—',pl:'staw',en:'pond',ex:'Ike ni sakana.',expl:'W stawie są ryby.',ety:'"źródło"',fun:'Japońskie ogrody mają stawy',part:'noun'},
  {cat:'nat2',e:'💦',r:'taki',m:'—',pl:'wodospad',en:'waterfall',ex:'Taki ga kirei.',expl:'Wodospad jest piękny.',ety:'spadająca woda',fun:'Trening ninja pod nim',part:'noun'},
  {cat:'nat2',e:'🏖️',r:'hama',m:'—',pl:'plaża',en:'beach',ex:'Hama de asobu.',expl:'Bawię się na plaży.',ety:'piasek+woda',fun:'Letnie wakacje',part:'noun'},
  {cat:'nat2',e:'🏝️',r:'shima',m:'—',pl:'wyspa',en:'island',ex:'Shima ni umi.',expl:'Morze wokół wyspy.',ety:'izolacja',fun:'Japonia to wyspy',part:'noun'},
  {cat:'nat2',e:'🏞️',r:'hanto',m:'—',pl:'półwysep',en:'peninsula',ex:'Hanto wa nagai.',expl:'Półwysep jest długi.',ety:'"pół-wyspa"',fun:'Geografia',part:'noun'},
  {cat:'nat2',e:'⛰️',r:'tani',m:'—',pl:'dolina',en:'valley',ex:'Tani ni kawa.',expl:'Rzeka w dolinie.',ety:'wklęsłość gór',fun:'Miejsce wiosek',part:'noun'},
  {cat:'nat2',e:'🕳️',r:'hora',m:'—',pl:'jaskinia',en:'cave',ex:'Hora ni hairu.',expl:'Wchodzę do jaskini.',ety:'puste miejsce',fun:'Loch / labirynt',part:'noun'},
  {cat:'nat2',e:'🏜️',r:'sabaku',m:'—',pl:'pustynia',en:'desert',ex:'Sabaku ga hiroi.',expl:'Pustynia jest rozległa.',ety:'"pusta ziemia"',fun:'Rzadkie w Japonii',part:'noun'},
  {cat:'nat2',e:'🌾',r:'nohara',m:'—',pl:'pole',en:'field',ex:'Nohara ga hiroi.',expl:'Pole jest rozległe.',ety:'pole uprawne',fun:'Ryżowe pola są święte',part:'noun'},
  {cat:'nat2',e:'🏖️',r:'suna',m:'—',pl:'piasek',en:'sand',ex:'Suna ga shiroi.',expl:'Piasek jest biały.',ety:'drobne ziarenka',fun:'Plaża',part:'noun'},
  {cat:'nat2',e:'💩',r:'doro',m:'—',pl:'błoto',en:'mud',ex:'Doro ga atsui.',expl:'Błoto jest gęste.',ety:'wilgotna ziemia',fun:'Po deszczu',part:'noun'},
  {cat:'nat2',e:'🧊',r:'koori',m:'—',pl:'lód',en:'ice',ex:'Koori ga tokeru.',expl:'Lód się topi.',ety:'zamrożona woda',fun:'Zimowy żywioł',part:'noun'},
  {cat:'nat2',e:'🌫️',r:'kiri',m:'—',pl:'mgła',en:'fog',ex:'Kiri ga atsui.',expl:'Mgła jest gęsta.',ety:'para',fun:'Tajemnicza atmosfera',part:'noun'},
  {cat:'nat2',e:'⚡',r:'kaminari',m:'—',pl:'grzmot',en:'thunder',ex:'Kaminari ga naru.',expl:'Grzmi.',ety:'"bóg dźwięku"',fun:'Dosłownie: bóg + dźwięk!',part:'noun'},
  {cat:'nat2',e:'🌩️',r:'inazuma',m:'—',pl:'błyskawica',en:'lightning',ex:'Inazuma ga hikaru.',expl:'Błyskawica świeci.',ety:'"ryżowa żona"',fun:'Etymologia legendarna',part:'noun'},
  {cat:'nat2',e:'🌪️',r:'tatsumaki',m:'—',pl:'tornado',en:'tornado',ex:'Tatsumaki ga kuru.',expl:'Nadchodzi tornado.',ety:'"zwój smoka"',fun:'Dosłownie: zwój + smok!',part:'noun'},
  {cat:'nat2',e:'🌊',r:'nami',m:'—',pl:'fala',en:'wave',ex:'Nami ga takai.',expl:'Fale są wysokie.',ety:'ruch wody',fun:'Tsunami - wielka fala',part:'noun'},
  {cat:'nat2',e:'🌅',r:'hinode',m:'—',pl:'wschód słońca',en:'sunrise',ex:'Hinode wo miru.',expl:'Patrzę na wschód.',ety:'dzień + wyjście',fun:'Magiczna pora',part:'noun'},
  {cat:'nat2',e:'🌇',r:'hinoire',m:'—',pl:'zachód słońca',en:'sunset',ex:'Hinoire ga akai.',expl:'Zachód jest czerwony.',ety:'dzień + wchodzenie',fun:'Romantyczny moment',part:'noun'},
  {cat:'zw1',e:'🐕',r:'inu',m:'—',pl:'pies',en:'dog',ex:'Inu ga hoeru.',expl:'Pies szczeka.',ety:'tradycja',fun:'Hachiko - legenda lojalności',part:'noun'},
  {cat:'zw1',e:'🐈',r:'neko',m:'—',pl:'kot',en:'cat',ex:'Neko ga naku.',expl:'Kot miauczy.',ety:'tradycja',fun:'Maneki-neko - przynosi szczęście',part:'noun'},
  {cat:'zw1',e:'🐦',r:'tori',m:'—',pl:'ptak',en:'bird',ex:'Tori ga tobu.',expl:'Ptak lata.',ety:'ogólnie',fun:'Podstawowe',part:'noun'},
  {cat:'zw1',e:'🐟',r:'sakana',m:'—',pl:'ryba',en:'fish',ex:'Sakana wo taberu.',expl:'Jem rybę.',ety:'woda',fun:'Częsta w kuchni',part:'noun'},
  {cat:'zw1',e:'🐎',r:'uma',m:'—',pl:'koń',en:'horse',ex:'Uma ni noru.',expl:'Jadę konno.',ety:'wierzchowiec',fun:'Samurajski symbol',part:'noun'},
  {cat:'zw1',e:'🐄',r:'ushi',m:'—',pl:'krowa',en:'cow',ex:'Ushi ga miruku.',expl:'Krowa daje mleko.',ety:'farmowe',fun:'Ważne w rolnictwie',part:'noun'},
  {cat:'zw1',e:'🐖',r:'buta',m:'—',pl:'świnia',en:'pig',ex:'Buta niku ga suki.',expl:'Lubię wieprzowinę.',ety:'farmowe',fun:'Tonkatsu - kotlet',part:'noun'},
  {cat:'zw1',e:'🐑',r:'hitsuji',m:'—',pl:'owca',en:'sheep',ex:'Hitsuji ga nemui.',expl:'Owce są senne.',ety:'farmowe',fun:'Wełna',part:'noun'},
  {cat:'zw1',e:'🐔',r:'niwatori',m:'—',pl:'kura',en:'chicken',ex:'Niwatori ga tamago.',expl:'Kura znosi jaja.',ety:'"ptak zagrody"',fun:'Podstawowe',part:'noun'},
  {cat:'zw1',e:'🐇',r:'usagi',m:'—',pl:'królik',en:'rabbit',ex:'Usagi ga hayai.',expl:'Królik jest szybki.',ety:'uszy długie',fun:'Księżycowy mit - usagi w księżycu',part:'noun'},
  {cat:'zw1',e:'🐻',r:'kuma',m:'—',pl:'niedźwiedź',en:'bear',ex:'Kuma ga aruku.',expl:'Niedźwiedź idzie.',ety:'dziki',fun:'W górach',part:'noun'},
  {cat:'zw1',e:'🐒',r:'saru',m:'—',pl:'małpa',en:'monkey',ex:'Saru ga asobu.',expl:'Małpa się bawi.',ety:'sprytny',fun:'Japońskie makaki',part:'noun'},
  {cat:'zw1',e:'🐘',r:'zou',m:'—',pl:'słoń',en:'elephant',ex:'Zou ga ookii.',expl:'Słoń jest duży.',ety:'olbrzym',fun:'Egzotyczny',part:'noun'},
  {cat:'zw1',e:'🦁',r:'raion',m:'—',pl:'lew',en:'lion',ex:'Raion ga tsuyoi.',expl:'Lew jest silny.',ety:'z angielskiego',fun:'Symbol odwagi',part:'noun'},
  {cat:'zw1',e:'🐅',r:'tora',m:'—',pl:'tygrys',en:'tiger',ex:'Tora ga kowai.',expl:'Tygrys jest straszny.',ety:'drapieżca',fun:'Znak zodiaku',part:'noun'},
  {cat:'zw1',e:'🐍',r:'hebi',m:'—',pl:'wąż',en:'snake',ex:'Hebi ga nagai.',expl:'Wąż jest długi.',ety:'długi gad',fun:'Znak zodiaku',part:'noun'},
  {cat:'zw1',e:'🐸',r:'kaeru',m:'—',pl:'żaba',en:'frog',ex:'Kaeru ga naku.',expl:'Żaba rechocze.',ety:'skaczący',fun:'Uwaga: "kaeru" = też wracać!',part:'noun'},
  {cat:'zw1',e:'🦋',r:'chou',m:'—',pl:'motyl',en:'butterfly',ex:'Chou ga tobu.',expl:'Motyl lata.',ety:'piękny owad',fun:'Symbol przemiany',part:'noun'},
  {cat:'zw1',e:'🐝',r:'hachi',m:'—',pl:'pszczoła',en:'bee',ex:'Hachi ga sasu.',expl:'Pszczoła żądli.',ety:'skrzydła',fun:'Miód = mitsu',part:'noun'},
  {cat:'zw1',e:'🐁',r:'nezumi',m:'—',pl:'mysz',en:'mouse',ex:'Nezumi ga chiisai.',expl:'Mysz jest mała.',ety:'gryzoń',fun:'Znak zodiaku',part:'noun'},
  {cat:'zw2',e:'🐺',r:'okami',m:'—',pl:'wilk',en:'wolf',ex:'Okami ga hoeru.',expl:'Wilk wyje.',ety:'dziki',fun:'Sacred w legendach',part:'noun'},
  {cat:'zw2',e:'🦊',r:'kitsune',m:'—',pl:'lis',en:'fox',ex:'Kitsune ga zurui.',expl:'Lis jest chytry.',ety:'magia',fun:'Może mieć do 9 ogonów!',part:'noun'},
  {cat:'zw2',e:'🦌',r:'shika',m:'—',pl:'jeleń',en:'deer',ex:'Shika ga shizuka.',expl:'Jeleń jest cichy.',ety:'las',fun:'Nara - miasto jeleni',part:'noun'},
  {cat:'zw2',e:'🐗',r:'inoshishi',m:'—',pl:'dzik',en:'boar',ex:'Inoshishi ga kowai.',expl:'Dzik jest groźny.',ety:'dziki',fun:'Znak zodiaku',part:'noun'},
  {cat:'zw2',e:'🐢',r:'kame',m:'—',pl:'żółw',en:'turtle',ex:'Kame ga yukkuri.',expl:'Żółw jest powolny.',ety:'powolność',fun:'Urashima Taro - legenda',part:'noun'},
  {cat:'zw2',e:'🐊',r:'wani',m:'—',pl:'krokodyl',en:'crocodile',ex:'Wani ga abunai.',expl:'Krokodyl jest niebezpieczny.',ety:'gad wodny',fun:'Rzadki',part:'noun'},
  {cat:'zw2',e:'🐧',r:'pengin',m:'—',pl:'pingwin',en:'penguin',ex:'Pengin ga samui.',expl:'Pingwinowi zimno.',ety:'z angielskiego',fun:'Popularny',part:'noun'},
  {cat:'zw2',e:'🐬',r:'iruka',m:'—',pl:'delfin',en:'dolphin',ex:'Iruka ga kashikoi.',expl:'Delfiny są mądre.',ety:'inteligentny',fun:'Morskie ssaki',part:'noun'},
  {cat:'zw2',e:'🦈',r:'same',m:'—',pl:'rekin',en:'shark',ex:'Same ga tsuyoi.',expl:'Rekin jest silny.',ety:'drapieżca morski',fun:'Niebezpieczny',part:'noun'},
  {cat:'zw2',e:'🐙',r:'tako',m:'—',pl:'ośmiornica',en:'octopus',ex:'Tako ga oishii.',expl:'Ośmiornica jest pyszna.',ety:'8 ramion',fun:'Uwaga: tako = też latawiec!',part:'noun'},
  {cat:'zw2',e:'🦀',r:'kani',m:'—',pl:'krab',en:'crab',ex:'Kani ga akai.',expl:'Krab jest czerwony.',ety:'skorupiak',fun:'Japońska kuchnia',part:'noun'},
  {cat:'zw2',e:'🕷️',r:'kumo',m:'—',pl:'pająk',en:'spider',ex:'Kumo no ito.',expl:'Nić pająka.',ety:'tka sieć',fun:'Uwaga: kumo = też chmura!',part:'noun'},
  {cat:'zw2',e:'🐜',r:'ari',m:'—',pl:'mrówka',en:'ant',ex:'Ari ga chiisai.',expl:'Mrówki są małe.',ety:'pracowity owad',fun:'Współpraca',part:'noun'},
  {cat:'zw2',e:'🪰',r:'hae',m:'—',pl:'mucha',en:'fly',ex:'Hae ga urusai.',expl:'Mucha jest irytująca.',ety:'szybki owad',fun:'Drobny',part:'noun'},
  {cat:'zw2',e:'🦟',r:'ka',m:'—',pl:'komar',en:'mosquito',ex:'Ka ga sasu.',expl:'Komar kąsa.',ety:'wampir',fun:'Letnia plaga',part:'noun'},
  {cat:'zw2',e:'🦉',r:'fukurou',m:'—',pl:'sowa',en:'owl',ex:'Fukurou ga kashikoi.',expl:'Sowa jest mądra.',ety:'nocny ptak',fun:'Symbol mądrości',part:'noun'},
  {cat:'zw2',e:'🦅',r:'washi',m:'—',pl:'orzeł',en:'eagle',ex:'Washi ga takai.',expl:'Orzeł lata wysoko.',ety:'krol ptaków',fun:'Potężny',part:'noun'},
  {cat:'zw2',e:'🦜',r:'oumu',m:'—',pl:'papuga',en:'parrot',ex:'Oumu ga hanasu.',expl:'Papuga mówi.',ety:'imitujący',fun:'Kolorowa',part:'noun'},
  {cat:'zw2',e:'🐹',r:'hamusuta',m:'—',pl:'chomik',en:'hamster',ex:'Hamusuta ga kawaii.',expl:'Chomik jest uroczy.',ety:'z angielskiego',fun:'Popularny pet',part:'noun'},
  {cat:'zw2',e:'🦒',r:'kirin',m:'—',pl:'żyrafa',en:'giraffe',ex:'Kirin ga takai.',expl:'Żyrafa jest wysoka.',ety:'mityczna',fun:'Uwaga: kirin = też jednorożec + piwo!',part:'noun'},
  {cat:'ani1',e:'⚔️',r:'yuusha',m:'—',pl:'bohater',en:'hero',ex:'Yuusha wa tsuyoi.',expl:'Bohater jest silny.',ety:'yuu = odwaga',fun:'Tytuł wybrańca',part:'noun'},
  {cat:'ani1',e:'👹',r:'akuma',m:'—',pl:'demon / diabeł',en:'demon',ex:'Akuma ga kuru.',expl:'Nadchodzi demon.',ety:'zło',fun:'Antagonista',part:'noun'},
  {cat:'ani1',e:'🧙',r:'mahou tsukai',m:'—',pl:'mag / czarodziej',en:'wizard',ex:'Mahou tsukai ga zen.',expl:'Mag jest dobry.',ety:'magia + użytkownik',fun:'Klasyczna klasa RPG',part:'noun'},
  {cat:'ani1',e:'🗡️',r:'katana',m:'—',pl:'miecz',en:'sword',ex:'Katana wo furuu.',expl:'Macham mieczem.',ety:'symbol samuraja',fun:'Dusza wojownika',part:'noun'},
  {cat:'ani1',e:'🛡️',r:'tate',m:'—',pl:'tarcza',en:'shield',ex:'Tate wo mochi.',expl:'Trzymam tarczę.',ety:'ochrona',fun:'Klasa bohatera',part:'noun'},
  {cat:'ani1',e:'🥋',r:'yoroi',m:'—',pl:'zbroja',en:'armor',ex:'Yoroi wo kiru.',expl:'Noszę zbroję.',ety:'ochrona ciała',fun:'Samurajskie',part:'noun'},
  {cat:'ani1',e:'✨',r:'mahou',m:'—',pl:'magia',en:'magic',ex:'Mahou wo tsukau.',expl:'Używam magii.',ety:'siła nadprzyrodzona',fun:'Różne elementy',part:'noun'},
  {cat:'ani1',e:'💪',r:'chikara',m:'—',pl:'moc / siła',en:'power',ex:'Chikara ga tsuyoi.',expl:'Moc jest silna.',ety:'ogólnie siła',fun:'Uniwersalne',part:'noun'},
  {cat:'ani1',e:'⚔️',r:'tatakai',m:'—',pl:'walka',en:'fight',ex:'Tatakai ga hajimaru.',expl:'Walka się zaczyna.',ety:'konflikt',fun:'W każdym isekai',part:'noun'},
  {cat:'ani1',e:'👿',r:'teki',m:'—',pl:'wróg',en:'enemy',ex:'Teki ga mieru.',expl:'Widzę wroga.',ety:'przeciwnik',fun:'Podstawowe',part:'noun'},
  {cat:'ani1',e:'🤝',r:'nakama',m:'—',pl:'sojusznik',en:'ally / comrade',ex:'Nakama to tatakau.',expl:'Walczę z sojusznikami.',ety:'towarzysz',fun:'NAJWAŻNIEJSZE słowo anime!',part:'noun'},
  {cat:'ani1',e:'👻',r:'tamashii',m:'—',pl:'dusza',en:'soul',ex:'Tamashii ga kiyoi.',expl:'Dusza jest czysta.',ety:'istota wewnętrzna',fun:'Częste w walkach',part:'noun'},
  {cat:'ani1',e:'🎭',r:'unmei',m:'—',pl:'przeznaczenie',en:'fate',ex:'Unmei wa kibishi.',expl:'Przeznaczenie jest srogie.',ety:'los',fun:'Filozofia isekai',part:'noun'},
  {cat:'ani1',e:'🌍',r:'sekai',m:'—',pl:'świat',en:'world',ex:'Sekai wo sukuu.',expl:'Ratuję świat.',ety:'planeta',fun:'Cel bohatera',part:'noun'},
  {cat:'ani1',e:'☁️',r:'tengoku',m:'—',pl:'niebo (raj)',en:'heaven',ex:'Tengoku e iku.',expl:'Idę do raju.',ety:'"pałac niebiański"',fun:'Po śmierci',part:'noun'},
  {cat:'ani1',e:'🔥',r:'jigoku',m:'—',pl:'piekło',en:'hell',ex:'Jigoku ga kowai.',expl:'Piekło jest straszne.',ety:'"więzienie ziemi"',fun:'Przeciwieństwo nieba',part:'noun'},
  {cat:'ani1',e:'🐉',r:'ryuu',m:'—',pl:'smok',en:'dragon',ex:'Ryuu ga tobu.',expl:'Smok lata.',ety:'magiczna bestia',fun:'Wschodni smok - dobry',part:'noun'},
  {cat:'ani1',e:'🏰',r:'shiro',m:'—',pl:'zamek',en:'castle',ex:'Shiro ni hairu.',expl:'Wchodzę do zamku.',ety:'twierdza',fun:'Siedziba maou',part:'noun'},
  {cat:'ani1',e:'📜',r:'densetsu',m:'—',pl:'legenda',en:'legend',ex:'Densetsu no yuusha.',expl:'Legendarny bohater.',ety:'przekaz',fun:'Każdy isekai ma',part:'noun'},
  {cat:'ani1',e:'🌀',r:'isekai',m:'—',pl:'inny świat',en:'other world',ex:'Isekai ni ikitai.',expl:'Chcę do innego świata.',ety:'"inny świat"',fun:'NAZWA TWOJEGO ŚWIATA!',part:'noun'},
  {cat:'ani2',e:'🥷',r:'ninja',m:'—',pl:'ninja',en:'ninja',ex:'Ninja ga kieru.',expl:'Ninja znika.',ety:'tradycja',fun:'Skryty wojownik',part:'noun'},
  {cat:'ani2',e:'🗡️',r:'samurai',m:'—',pl:'samuraj',en:'samurai',ex:'Samurai no michi.',expl:'Droga samuraja.',ety:'"służący"',fun:'Bushido',part:'noun'},
  {cat:'ani2',e:'💂',r:'senshi',m:'—',pl:'wojownik',en:'warrior',ex:'Senshi ga tsuyoi.',expl:'Wojownik jest silny.',ety:'"walczący"',fun:'Klasa RPG',part:'noun'},
  {cat:'ani2',e:'🧑‍🎓',r:'seito',m:'—',pl:'uczeń / uczniak',en:'student',ex:'Seito ga benkyou.',expl:'Uczeń się uczy.',ety:'"wychowanek"',fun:'Dojo',part:'noun'},
  {cat:'ani2',e:'🧙‍♂️',r:'shishou',m:'—',pl:'mistrz',en:'master',ex:'Shishou ga oshieru.',expl:'Mistrz naucza.',ety:'wielki nauczyciel',fun:'Czcigodny',part:'noun'},
  {cat:'ani2',e:'💪',r:'shugyou',m:'—',pl:'trening',en:'training',ex:'Shugyou ga kibishi.',expl:'Trening jest srogi.',ety:'praktyka',fun:'Ninja i samuraje',part:'noun'},
  {cat:'ani2',e:'⚡',r:'waza',m:'—',pl:'technika / atak',en:'technique',ex:'Waza ga kirei.',expl:'Technika jest piękna.',ety:'umiejętność',fun:'Konkretny cios',part:'noun'},
  {cat:'ani2',e:'📊',r:'reberu',m:'—',pl:'poziom',en:'level',ex:'Reberu ga agaru.',expl:'Poziom rośnie.',ety:'z angielskiego',fun:'RPG mechanika',part:'noun'},
  {cat:'ani2',e:'⭐',r:'keiken',m:'—',pl:'doświadczenie',en:'experience',ex:'Keiken wo eru.',expl:'Zdobywam doświadczenie.',ety:'nauka z akcji',fun:'XP!',part:'noun'},
  {cat:'ani2',e:'🎯',r:'misshon',m:'—',pl:'misja',en:'mission',ex:'Misshon wo kansei.',expl:'Kończę misję.',ety:'z angielskiego',fun:'Zadanie',part:'noun'},
  {cat:'ani2',e:'🏛️',r:'girudo',m:'—',pl:'gildia',en:'guild',ex:'Girudo ni hairu.',expl:'Wstępuję do gildii.',ety:'z angielskiego',fun:'Organizacja awanturników',part:'noun'},
  {cat:'ani2',e:'👾',r:'monsuta',m:'—',pl:'potwór',en:'monster',ex:'Monsuta wo taosu.',expl:'Pokonuję potwora.',ety:'z angielskiego',fun:'Wróg do farmienia',part:'noun'},
  {cat:'ani2',e:'💀',r:'gaikotsu',m:'—',pl:'szkielet',en:'skeleton',ex:'Gaikotsu ga odoru.',expl:'Szkielet tańczy.',ety:'"zewnętrzne kości"',fun:'Nieumarły',part:'noun'},
  {cat:'ani2',e:'👻',r:'yurei',m:'—',pl:'duch',en:'ghost',ex:'Yurei ga kowai.',expl:'Duch jest straszny.',ety:'"błąkająca się dusza"',fun:'Nawiedza żywych',part:'noun'},
  {cat:'ani2',e:'🌸',r:'megami',m:'—',pl:'bogini',en:'goddess',ex:'Megami ga utsukushii.',expl:'Bogini jest piękna.',ety:'"pani bóstw"',fun:'Często oferuje isekai',part:'noun'},
  {cat:'ani2',e:'⛩️',r:'kami',m:'—',pl:'bóg',en:'god',ex:'Kami-sama ga miru.',expl:'Bóg patrzy.',ety:'bóstwo',fun:'Uwaga: kami = też papier i włosy!',part:'noun'},
  {cat:'ani2',e:'🩸',r:'chi',m:'—',pl:'krew',en:'blood',ex:'Chi ga nagareru.',expl:'Krew płynie.',ety:'płyn życia',fun:'Chidori z Naruto',part:'noun'},
  {cat:'ani2',e:'💧',r:'namida',m:'—',pl:'łzy',en:'tears',ex:'Namida ga deru.',expl:'Płyną łzy.',ety:'płacz',fun:'Dramat anime',part:'noun'},
  {cat:'ani2',e:'🗡️',r:'fukushuu',m:'—',pl:'zemsta',en:'revenge',ex:'Fukushuu wo chikau.',expl:'Przysięgam zemstę.',ety:'"odwet"',fun:'Motywacja antagonisty',part:'noun'},
  {cat:'ani2',e:'🌟',r:'kibou',m:'—',pl:'nadzieja',en:'hope',ex:'Kibou wo motsu.',expl:'Mam nadzieję.',ety:'"pragnienie"',fun:'W finałach shonen',part:'noun'},
  {cat:'ani3',e:'🔮',r:'shoukan',m:'—',pl:'przyzwanie',en:'summoning',ex:'Shoukan jutsu.',expl:'Technika przyzwania.',ety:'"wołanie"',fun:'Do innego świata',part:'noun'},
  {cat:'ani3',e:'⚔️',r:'sukiru',m:'—',pl:'umiejętność',en:'skill',ex:'Sukiru wo eru.',expl:'Zdobywam umiejętność.',ety:'z angielskiego',fun:'RPG',part:'noun'},
  {cat:'ani3',e:'📋',r:'suteesu',m:'—',pl:'status',en:'status',ex:'Suteesu wo miru.',expl:'Widzę status.',ety:'z angielskiego',fun:'Ekran gry',part:'noun'},
  {cat:'ani3',e:'🎒',r:'soubi',m:'—',pl:'ekwipunek',en:'equipment',ex:'Soubi wo kaeru.',expl:'Zmieniam ekwipunek.',ety:'"wyposażenie"',fun:'Inventory',part:'noun'},
  {cat:'ani3',e:'💚',r:'kaifuku',m:'—',pl:'leczenie',en:'healing',ex:'Kaifuku majutsu.',expl:'Magia leczenia.',ety:'"odnowa"',fun:'Healer klasa',part:'noun'},
  {cat:'ani3',e:'🧪',r:'doku',m:'—',pl:'trucizna',en:'poison',ex:'Doku ga kowai.',expl:'Trucizna jest groźna.',ety:'zagrożenie',fun:'Status effect',part:'noun'},
  {cat:'ani3',e:'💀',r:'norowareta',m:'—',pl:'przeklęty',en:'cursed',ex:'Norowareta buki.',expl:'Przeklęta broń.',ety:'klątwa',fun:'Negatywny buff',part:'noun'},
  {cat:'ani3',e:'🌟',r:'shukufuku sareta',m:'—',pl:'błogosławiony',en:'blessed',ex:'Shukufuku sareta.',expl:'Błogosławiony.',ety:'łaska',fun:'Pozytywny buff',part:'noun'},
  {cat:'ani3',e:'🌀',r:'geeuto',m:'—',pl:'portal / brama',en:'gate',ex:'Geeuto wo akeru.',expl:'Otwieram portal.',ety:'z angielskiego',fun:'Transport',part:'noun'},
  {cat:'ani3',e:'🌀',r:'meikyuu',m:'—',pl:'labirynt / loch',en:'dungeon',ex:'Meikyuu wo kouryaku.',expl:'Zdobywam loch.',ety:'"zagubienie"',fun:'Dungeon crawl',part:'noun'},
  {cat:'ani3',e:'🪽',r:'tsubasa',m:'—',pl:'skrzydła',en:'wings',ex:'Tsubasa ga haeru.',expl:'Wyrastają skrzydła.',ety:'lot',fun:'Anielskie/demoniczne',part:'noun'},
  {cat:'ani3',e:'〰️',r:'shippo',m:'—',pl:'ogon',en:'tail',ex:'Shippo wo furu.',expl:'Macha ogonem.',ety:'zwierzęce',fun:'Kemonomimi',part:'noun'},
  {cat:'ani3',e:'🐺',r:'kemonomimi',m:'—',pl:'uszy zwierzęce',en:'beast ears',ex:'Kemonomimi ga kawaii.',expl:'Uszy zwierzęce są słodkie.',ety:'"uszy bestii"',fun:'Anime trope',part:'noun'},
  {cat:'ani3',e:'🧝',r:'erufu',m:'—',pl:'elf',en:'elf',ex:'Erufu wa nagaiki.',expl:'Elfy żyją długo.',ety:'z angielskiego',fun:'Klasyczna rasa',part:'noun'},
  {cat:'ani3',e:'⛏️',r:'doroofu',m:'—',pl:'krasnolud',en:'dwarf',ex:'Doroofu wa chikara.',expl:'Krasnolud to siła.',ety:'z angielskiego',fun:'Kowal / górnik',part:'noun'},
  {cat:'ani3',e:'♾️',r:'fujimi',m:'—',pl:'nieśmiertelny',en:'immortal',ex:'Fujimi no karada.',expl:'Nieśmiertelne ciało.',ety:'"bez śmierci"',fun:'Fantasy element',part:'noun'},
  {cat:'ani3',e:'♻️',r:'tensei',m:'—',pl:'odrodzenie',en:'reincarnation',ex:'Tensei shita yuusha.',expl:'Odrodzony bohater.',ety:'"nowe życie"',fun:'W co 2 isekai!',part:'noun'},
  {cat:'ani3',e:'💭',r:'kioku',m:'—',pl:'wspomnienia',en:'memories',ex:'Kioku wo torimodosu.',expl:'Odzyskuję wspomnienia.',ety:'pamięć',fun:'Amnezja trope',part:'noun'},
  {cat:'ani3',e:'📜',r:'keiyaku',m:'—',pl:'kontrakt / umowa',en:'contract',ex:'Keiyaku wo musubu.',expl:'Zawieram kontrakt.',ety:'wiążąca umowa',fun:'Demoniczny pakt',part:'noun'},
  {cat:'ani3',e:'👑',r:'taitoru',m:'—',pl:'tytuł / ranga',en:'title',ex:'Taitoru wo eru.',expl:'Zdobywam tytuł.',ety:'z angielskiego',fun:'Achievement',part:'noun'}
];
const EXTRAS=[ {r:'watashi',pl:'ja',en:'I',e:'🧑',cat:'extra',part:'subject'}, {r:'anata',pl:'ty',en:'you',e:'👤',cat:'extra',part:'subject'}, {r:'wa',pl:'[temat]',en:'topic marker',e:'📌',cat:'extra',part:'particle'}, {r:'wo',pl:'[obiekt]',en:'object marker',e:'🎯',cat:'extra',part:'particle'}, {r:'ni',pl:'[do/w]',en:'direction/location',e:'📍',cat:'extra',part:'particle'}, {r:'de',pl:'[w/przez]',en:'place of action',e:'🔧',cat:'extra',part:'particle'}, {r:'ga',pl:'[podmiot]',en:'subject marker',e:'⭐',cat:'extra',part:'particle'} ];
const ALL_WORDS = [...D, ...EXTRAS];
const GAME_WORDS = D.filter(w => w.pl && w.r); // Do gry bierzemy tylko pełne słówka
const BOOK_CHAPTERS = {
  particles: {
    title: "Złote Partykuły", theme: "gold", seal: "✧",
    entries: [
      {r:'は', r_r:'wa', t:'Runa Tematu (WA)', d:'Wyznacza ogólny temat zdania.', ex:'Watashi <b>wa</b> yuusha desu.', expl:'Ja jestem bohaterem.', akemi:'"Wa" to światło sceny.'},
      {r:'が', r_r:'ga', t:'Runa Podmiotu (GA)', d:'Wyznacza podmiot. Kładzie nacisk na "kto".', ex:'Watashi <b>ga</b> yuusha desu.', expl:'To JA jestem bohaterem.', akemi:'Używaj "ga" w pytaniach o sprawcę.'},
      {r:'を', r_r:'wo', t:'Runa Celu (WO)', d:'Oznacza dopełnienie bliższe.', ex:'Ringo <b>wo</b> tabemasu.', expl:'Jem jabłko.', akemi:'Traktuj "wo" jako magiczną strzałę wbitą w cel.'},
      {r:'に', r_r:'ni', t:'Runa Punktu (NI)', d:'Wskazuje cel ruchu, czas.', ex:'Isekai <b>ni</b> ikimasu.', expl:'Idę do innego świata.', akemi:'Kierunek podróży zawsze oznacza NI.'},
    ], prev: 'toc', next: 'tenses'
  },
  tenses: {
    title: "Władza nad Czasem", theme: "fire", seal: "♨",
    entries: [
      {r:'ます', r_r:'-masu', t:'Teraźniejszy/Przyszły', d:'Grzeczna forma akcji.', ex:'Ringo wo tabe<b>masu</b>.', expl:'Jem jabłko.', akemi:'Teraźniejszość płonie tak samo jak przyszłość.'},
      {r:'ません', r_r:'-masen', t:'Przeczenie', d:'Zamień "masu" na "masen".', ex:'Watashi wa iki<b>masen</b>.', expl:'Ja nie idę.', akemi:'Brak akcji to też akcja. "Masen" to tarcza.'},
      {r:'ました', r_r:'-mashita', t:'Czas Przeszły', d:'Dla zdarzeń, które już minęły.', ex:'Hon wo yomi<b>mashita</b>.', expl:'Przeczytałem książkę.', akemi:'Popioły przeszłości wyraża "mashita".'}
    ], prev: 'particles', next: 'other'
  },
  other: {
    title: "Inne Prawa Magii", theme: "nature", seal: "❀",
    entries: [
      {r:'い/な', r_r:'-i / -na', t:'Królowe Przymiotników', d:'Podział przymiotników na i- oraz na-.', ex:'Atarashi<b>i</b> hon.', expl:'Nowa książka.', akemi:'Przymiotniki "i" rosną i odmieniają się same.'},
      {r:'たい', r_r:'-tai', t:'Zaklęcie Życzenia', d:'Służy do wyrażania chęci.', ex:'Isekai ni iki<b>tai</b> desu.', expl:'Chcę pójść do innego świata.', akemi:'"Tai" wyrasta z rdzenia słowa niczym nowy pęd.'},
    ], prev: 'tenses', next: 'toc'
  }
};
const YUMI_TIPS = {
  init: 'Witaj w Bibliotece! Jestem Yumi. Zawsze będę tu, by podpowiedzieć ci, do czego służy dana strona.',
  slownik: '📚 Leksykon. Kliknij kartę, aby odkryć ukryte w niej zakładki i sekrety!',
  gramatyka: '✦ Księga Arkanów! Spójrz na tę wspaniałą oprawę 3D. Przerzucaj strony, a zobaczysz magię.',
  dojo: '⚔️ Próba Dojo. To tu sprawdzisz, czego się nauczyłeś. Zbieraj combo many!',
  zdania: '✏️ Stół Alchemiczny. Złóż słowa z Banku. Kliknij "Wymuś SOV", a sama ułożę ci poprawny szyk!',
  chat: '🔮 Mistrzyni Akemi! Ona potrafi przetłumaczyć ci całe zdania na japoński.',
  gildia: '🏛️ Twoja Gildia! Powtórki SRS, statystyki, Skarbiec - wszystko w jednym miejscu!'
};
const DOJO_REWARDS = [
  // CIEKAWOSTKI O JAPONII
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'W Japonii istnieje <b>ponad 6800 wysp</b>, choć zamieszkanych jest tylko około 430. Cztery główne to Honshu, Hokkaido, Kyushu i Shikoku.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'Japońskie słowo <b>"komorebi"</b> (木漏れ日) oznacza "promienie słońca przeświecające przez liście drzew". Nie ma swojego odpowiednika w polskim ani angielskim.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'W Japonii produkuje się <b>ponad 200 smaków Kit Kat</b>, w tym sake, wasabi, słodki kartofel i zielona herbata. Słowo "Kit Kat" brzmi podobnie do <i>"kitto katsu"</i> — "na pewno wygrasz".' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: '<b>Hanami</b> (花見) to tradycja oglądania kwitnących wiśni sakura. Telewizja codziennie podaje "prognozę kwitnienia", która przesuwa się z południa na północ kraju.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'W Japonii są <b>automaty do wszystkiego</b> — od ciepłej ramen po świeże jajka. Jest ich około 5 milionów, jeden na 23 mieszkańców!' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: '<b>Shinrin-yoku</b> (森林浴, "kąpiel leśna") to uznana praktyka medyczna w Japonii. Lekarze przepisują spacery po lesie jako terapię stresu.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'W japońskim jest <b>ponad 50 słów na "ja"</b>: watashi, boku, ore, atashi, washi, kocchi... Każde niesie informację o płci, wieku, statusie i relacji z rozmówcą.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'Pociąg <b>Shinkansen</b> spóźnia się średnio o <b>54 sekundy rocznie</b>. Jeśli zdarzy się spóźnienie powyżej 5 minut, wydawane są zaświadczenia dla pracodawców.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: '<b>Kintsugi</b> (金継ぎ) to sztuka naprawy złamanej ceramiki złotem. Filozofia: pęknięcia są częścią historii obiektu i należy je eksponować, nie ukrywać.' },
  { type: 'ciekawostka', title: '🗾 Ciekawostka o Japonii', text: 'W języku japońskim <b>liczenie ludzi, zwierząt, płaskich rzeczy i cylindrów</b> używa innych sufiksów. "Dwa koty" to <i>neko ni-hiki</i>, ale "dwie osoby" to <i>futari</i>.' },

  // REKOMENDACJE ANIME ISEKAI
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Re:Zero − Starting Life in Another World</b><br><i>リゼロ</i><br>Subaru trafia do świata fantasy z mocą cofania się w czasie po śmierci. Psychologicznie ciężkie, ale genialne. Idealne dla fanów angstu i dobrej narracji.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Konosuba: God\'s Blessing on This Wonderful World</b><br><i>この素晴らしい世界に祝福を！</i><br>Komediowa parodia gatunku isekai. Kazuma i jego beznadziejna drużyna: bogini-idiotka, pyromanka-explosionomaniaczka i rycerka-masochistka.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Overlord</b><br><i>オーバーロード</i><br>Gracz MMO zostaje uwięziony w swoim ciele szkieleta-lisza. Protagonista-antagonista buduje imperium. Jeśli lubisz "kami" i "gaikotsu", ten jest dla ciebie!' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Mushoku Tensei: Jobless Reincarnation</b><br><i>無職転生</i><br>Gold-standard współczesnego isekai. Rudeus odradza się w świecie magii z pamięcią poprzedniego życia. Wspaniała animacja i worldbuilding.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>That Time I Got Reincarnated as a Slime</b><br><i>転生したらスライムだった件</i><br>Rimuru odradza się jako slime z mocą pożerania zdolności. Buduje utopię dla demi-ludzi. Komfortowe "power fantasy" z dobrym sercem.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Log Horizon</b><br><i>ログ・ホライズン</i><br>30 tysięcy graczy utknęło w świecie MMO. Zamiast walki o przetrwanie — polityka, ekonomia i dyplomacja. Dla tych co lubią Sword Art Online, ale chcą mądrzej.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>The Rising of the Shield Hero</b><br><i>盾の勇者の成り上がり</i><br>Naofumi zostaje wezwany jako bohater Tarczy, najsłabsza klasa. Zdradzony i pogardzany, buduje swoją drużynę od zera. Dark fantasy isekai z sercem.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>No Game No Life</b><br><i>ノーゲーム・ノーライフ</i><br>Rodzeństwo-geniusze zostaje przeniesionych do świata, gdzie wszystko rozstrzygają gry. Fenomenalna paleta kolorów i inteligentna strategia.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Sousou no Frieren</b><br><i>葬送のフリーレン</i><br>Elfka po pokonaniu Króla Demonów podróżuje dekadami po świecie. Melancholijna medytacja nad czasem, przyjaźnią i znaczeniem życia. Arcydzieło.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Isekai', text: '<b>Ascendance of a Bookworm</b><br><i>本好きの下剋上</i><br>Bibliofilka odradza się jako chorowita dziewczynka w świecie bez książek. Postanawia... wynaleźć papier i druk. Wolny, mądry, satysfakcjonujący isekai.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Dark Fantasy', text: '<b>Berserk</b><br><i>ベルセルク</i><br>Guts, miecznik z ogromnym mieczem, poluje na demony. Mroczne, brutalne arcydzieło dark fantasy. Manga Miury jest wzorem dla całego gatunku.' },
  { type: 'anime', title: '✨ Rekomendacja Anime Fantasy', text: '<b>Made in Abyss</b><br><i>メイドインアビス</i><br>Pięknie animowany świat otchłani pełnej potworów. Cute-deceptive — wygląda uroczo, ale to jedna z najmroczniejszych opowieści w anime.' }
];
const GRAMMAR_QUESTIONS = [
  { q: 'Która partykuła oznacza <b>temat zdania</b>?', opts: ['wa (は)', 'wo (を)', 'ga (が)', 'de (で)'], correct: 0, expl: '"wa" (pisane znakiem は) ogłasza temat — "jeśli chodzi o X".' },
  { q: 'Która partykuła oznacza <b>dopełnienie bliższe</b>?', opts: ['ni (に)', 'wo (を)', 'no (の)', 'to (と)'], correct: 1, expl: '"wo" (を) to strzała wymierzona w cel czasownika.' },
  { q: 'Jaki jest szyk zdania po japońsku?', opts: ['SVO (Podmiot-Czasownik-Dopełnienie)', 'VSO', 'SOV (Podmiot-Dopełnienie-Czasownik)', 'OVS'], correct: 2, expl: 'Japoński to język SOV — czasownik zawsze na końcu.' },
  { q: 'Która forma to <b>grzeczny czas teraźniejszy/przyszły</b>?', opts: ['-masen', '-mashita', '-masu', '-te'], correct: 2, expl: '"-masu" to forma grzeczna dla akcji obecnych i przyszłych.' },
  { q: 'Jak zaprzeczyć akcji w formie grzecznej?', opts: ['-masen', '-mashita', '-te kudasai', '-tai'], correct: 0, expl: 'Zamień "masu" na "masen": tabemasu → tabemasen.' },
  { q: 'Jak powiesz <b>"czytałem książkę"</b>?', opts: ['Hon wo yomimasu', 'Hon wo yomitai desu', 'Hon wo yomimashita', 'Hon wa yomimasen'], correct: 2, expl: '"-mashita" to czas przeszły grzeczny.' },
  { q: 'Która partykuła oznacza <b>cel ruchu</b> (np. "do szkoły")?', opts: ['de (で)', 'ni (に)', 'wo (を)', 'ga (が)'], correct: 1, expl: '"ni" wskazuje punkt docelowy, moment w czasie, miejsce istnienia.' },
  { q: 'Która partykuła oznacza <b>miejsce akcji</b> (np. "w szkole się uczę")?', opts: ['de (で)', 'ni (に)', 'to (と)', 'wa (は)'], correct: 0, expl: '"de" = arena, gdzie toczy się akcja. "Gakkou DE benkyou shimasu" = Uczę się w szkole.' },
  { q: 'Co znaczy "<b>-tai</b>" na końcu czasownika?', opts: ['przeczenie', 'chęć/pragnienie', 'czas przeszły', 'prośba'], correct: 1, expl: '"-tai" = "chcę". Ikitai = chcę iść.' },
  { q: '<b>i-przymiotniki</b> kończą się na:', opts: ['-i', '-na', '-no', '-ka'], correct: 0, expl: 'np. atarashii (nowy), takai (wysoki), kawaii (słodki).' },
  { q: 'Która partykuła oznacza <b>posiadanie/przynależność</b>?', opts: ['wa (は)', 'no (の)', 'ga (が)', 'de (で)'], correct: 1, expl: 'Watashi NO hon = MOJA książka. Szyk: Posiadacz + NO + Obiekt.' },
  { q: 'Jak powiesz "<b>piję wodę</b>"?', opts: ['Mizu wa nomimasu', 'Mizu wo nomimasu', 'Mizu de nomimasu', 'Mizu ga nomimasu'], correct: 1, expl: 'Woda (mizu) to dopełnienie → potrzebujesz WO.' },
  { q: 'Co znaczy "<b>desu</b>" na końcu zdania?', opts: ['nie-czasownik "być"', 'pytanie', 'przeczenie', 'rozkaz'], correct: 0, expl: '"desu" to grzeczny łącznik "jest/być". Watashi wa gakusei desu = Jestem studentem.' },
  { q: 'Która partykuła tworzy <b>pytanie</b>?', opts: ['ka (か)', 'yo (よ)', 'ne (ね)', 'mo (も)'], correct: 0, expl: 'Genki desu KA? = Jak się masz? (pytajnik na końcu zdania).' },
  { q: 'Forma <b>-te kudasai</b> to:', opts: ['przeczenie', 'prośba ("proszę")', 'życzenie', 'przeszłość'], correct: 1, expl: 'Tabete kudasai! = Proszę zjedz. Grzeczna prośba.' },
  { q: 'Która partykuła oznacza "<b>z kimś</b>" (towarzystwo)?', opts: ['de (で)', 'ni (に)', 'to (と)', 'ga (が)'], correct: 2, expl: 'Tomodachi TO ikimasu = Idę z przyjacielem.' },
  { q: 'Jak powiesz "<b>chcę iść do szkoły</b>"?', opts: ['Gakkou ni ikimasu', 'Gakkou ni ikitai desu', 'Gakkou wo ikimasen', 'Gakkou de ikitai'], correct: 1, expl: 'iku → iki + tai + desu. Partykuła NI dla celu ruchu.' },
  { q: 'Czy podmiot zawsze musi być wypowiedziany?', opts: ['Tak, zawsze', 'Nie — można go pominąć gdy jasny z kontekstu', 'Tylko w pytaniach', 'Tylko w przeczeniach'], correct: 1, expl: 'Japoński często pomija podmiot. "Tabemasu" może znaczyć "Jem" bez "watashi wa".' },
  { q: 'Co znaczy <b>"kitsune"</b>?', opts: ['bohater', 'lis', 'magia', 'demon'], correct: 1, expl: 'Kitsune (狐) = lis. Magiczne stworzenie z mitologii japońskiej, może mieć do 9 ogonów.' },
  { q: 'Co znaczy <b>"yuusha"</b>?', opts: ['książę', 'bohater', 'czarnoksiężnik', 'smok'], correct: 1, expl: 'Yuusha (勇者) = bohater. Klasyczny tytuł w każdym isekai!' }
];
const FORGE_QUESTIONS = [
  // poziom podstawowy (słówka) - generated dynamically z D
  // poziom średni (frazy)
  { q: 'Jak powiesz "Jem jabłko"?', a: ['ringo wo tabemasu'], hint: '🍎 ringo + を + たべます' },
  { q: 'Jak powiesz "Piję wodę"?', a: ['mizu wo nomimasu'], hint: '💧 mizu + を + のみます' },
  { q: 'Jak powiesz "Czytam książkę"?', a: ['hon wo yomimasu'], hint: '📖 hon + を + よみます' },
  { q: 'Jak powiesz "Oglądam anime"?', a: ['anime wo mimasu'], hint: '📺 anime + を + みます' },
  { q: 'Jak powiesz "Jestem studentem"?', a: ['watashi wa gakusei desu'], hint: '🧑 watashi + は + gakusei + です' },
  { q: 'Jak powiesz "Lubię japoński"?', a: ['nihongo ga suki desu'], hint: '🇯🇵 nihongo + が + suki + です' },
  { q: 'Jak powiesz "Idę do szkoły"?', a: ['gakkou ni ikimasu'], hint: '🏫 gakkou + に + いきます' },
  { q: 'Jak powiesz "Wracam do domu"?', a: ['uchi ni kaerimasu', 'ie ni kaerimasu'], hint: '🏠 uchi/ie + に + かえります' },
  { q: 'Jak powiesz "Chcę iść"?', a: ['ikitai desu'], hint: '➤ iku → iki + tai + desu' },
  { q: 'Jak powiesz "Nie idę" (grzecznie)?', a: ['ikimasen'], hint: '🚫 iku → ikimasen (przeczenie)' },
  { q: 'Jak powiesz "Przeczytałem książkę"?', a: ['hon wo yomimashita'], hint: '📖 hon + を + yomimashita (przeszły)' },
  { q: 'Jak powiesz "W lesie jest lis"?', a: ['mori ni kitsune ga imasu'], hint: '🦊 mori + に + kitsune + が + います' },
  { q: 'Jak powiesz "Dzień dobry (rano)"?', a: ['ohayou', 'ohayou gozaimasu'], hint: '☀️ Rano, mniej formalnie' },
  { q: 'Jak powiesz "Dziękuję"?', a: ['arigatou', 'arigatou gozaimasu', 'doumo arigatou'], hint: '🙏 Podstawowa forma' },
  { q: 'Jak powiesz "Przepraszam"?', a: ['sumimasen', 'gomen', 'gomennasai'], hint: '🙇 Najbardziej uniwersalne słowo' },
  { q: 'Partykuła oznaczająca temat zdania:', a: ['wa', 'は'], hint: '📌 "Jeśli chodzi o X..."' },
  { q: 'Partykuła oznaczająca dopełnienie (obiekt czasownika):', a: ['wo', 'o', 'を'], hint: '🎯 Strzała w cel czasownika' },
  { q: 'Partykuła oznaczająca miejsce akcji (np. "W szkole się uczę"):', a: ['de', 'で'], hint: '⚔️ Arena akcji' },
  { q: 'Partykuła oznaczająca cel ruchu (np. "Idę do szkoły"):', a: ['ni', 'に'], hint: '📍 Punkt docelowy' },
  { q: 'Co znaczy "kitsune" (po polsku)?', a: ['lis', 'lisa'], hint: '🦊 Zwierzę z mitologii, do 9 ogonów' },
  { q: 'Co znaczy "yuusha" (po polsku)?', a: ['bohater', 'bohatera'], hint: '⚔️ Tytuł w isekai' },
  { q: 'Co znaczy "maou" (po polsku)?', a: ['król demonów', 'demon', 'władca demonów'], hint: '👹 Antagonist isekai' },
  { q: 'Co znaczy "ryuu" (po polsku)?', a: ['smok', 'smoka'], hint: '🐉 Istota powietrza i wody' },
  { q: 'Co znaczy "ken" (po polsku)?', a: ['miecz', 'miecza'], hint: '⚔️ Broń samuraja' }
];
const ECHO_ITEMS = [
  { jp: 'ringo wo tabemasu', pl: 'Jem jabłko', lvl: 'N5' },
  { jp: 'mizu wo nomimasu', pl: 'Piję wodę', lvl: 'N5' },
  { jp: 'hon wo yomimasu', pl: 'Czytam książkę', lvl: 'N5' },
  { jp: 'anime wo mimasu', pl: 'Oglądam anime', lvl: 'N5' },
  { jp: 'watashi wa gakusei desu', pl: 'Jestem studentem', lvl: 'N5' },
  { jp: 'nihongo ga suki desu', pl: 'Lubię japoński', lvl: 'N5' },
  { jp: 'gakkou ni ikimasu', pl: 'Idę do szkoły', lvl: 'N5' },
  { jp: 'uchi ni kaerimasu', pl: 'Wracam do domu', lvl: 'N5' },
  { jp: 'ohayou gozaimasu', pl: 'Dzień dobry', lvl: 'N5' },
  { jp: 'arigatou gozaimasu', pl: 'Dziękuję bardzo', lvl: 'N5' },
  { jp: 'sumimasen', pl: 'Przepraszam', lvl: 'N5' },
  { jp: 'wakarimashita', pl: 'Zrozumiałem', lvl: 'N5' },
  { jp: 'kitsune', pl: 'lis', lvl: 'N5' },
  { jp: 'yuusha', pl: 'bohater', lvl: 'N5' },
  { jp: 'ryuu', pl: 'smok', lvl: 'N5' },
  { jp: 'maou', pl: 'król demonów', lvl: 'N5' },
  { jp: 'mori ni kitsune ga imasu', pl: 'W lesie jest lis', lvl: 'N4' },
  { jp: 'yuusha wa tsuyoi desu', pl: 'Bohater jest silny', lvl: 'N4' },
  { jp: 'ringo wo tabemashita', pl: 'Zjadłem jabłko', lvl: 'N4' },
  { jp: 'gakkou ni ikitai desu', pl: 'Chcę iść do szkoły', lvl: 'N4' }
];
const PL_TO_ROMAJI = {
  // zaimki
  'ja':'watashi', 'ty':'anata', 'on':'kare', 'ona':'kanojo', 'my':'watashitachi', 'wy':'anatatachi', 'oni':'karera',
  // czasowniki + odmiany
  'jeść':'taberu', 'jem':'taberu', 'jesz':'taberu', 'je':'taberu', 'jedzą':'taberu', 'jemy':'taberu', 'jecie':'taberu',
  'pić':'nomu', 'piję':'nomu', 'pijesz':'nomu', 'pije':'nomu', 'piją':'nomu', 'pijemy':'nomu',
  'iść':'iku', 'idę':'iku', 'idziesz':'iku', 'idzie':'iku', 'idą':'iku', 'idziemy':'iku', 'pójść':'iku', 'pójdę':'iku', 'pójdzie':'iku',
  'przyjść':'kuru', 'przychodzę':'kuru', 'przychodzi':'kuru', 'przyszedłem':'kuru', 'przyjdzie':'kuru',
  'wracać':'kaeru', 'wracam':'kaeru', 'wracasz':'kaeru', 'wraca':'kaeru', 'wrócę':'kaeru', 'wróci':'kaeru',
  'kupować':'kau', 'kupuję':'kau', 'kupuje':'kau', 'kupić':'kau', 'kupił':'kau',
  'rozumieć':'wakaru', 'rozumiem':'wakaru', 'rozumiesz':'wakaru', 'rozumie':'wakaru',
  'wiedzieć':'shiru', 'wiem':'shiru', 'wiesz':'shiru', 'wie':'shiru', 'znać':'shiru', 'znam':'shiru',
  'lubić':'suki da', 'lubię':'suki da', 'lubi':'suki da', 'lubisz':'suki da', 'podoba':'suki da',
  'chcieć':'hoshii', 'chcę':'hoshii', 'chce':'hoshii', 'chcesz':'hoshii',
  'mówić':'hanasu', 'mówię':'hanasu', 'mówi':'hanasu', 'mówisz':'hanasu', 'powiedzieć':'hanasu', 'powiem':'hanasu',
  'słuchać':'kiku', 'słucham':'kiku', 'słucha':'kiku', 'słuchasz':'kiku', 'słyszeć':'kiku',
  'oglądać':'miru', 'oglądam':'miru', 'ogląda':'miru', 'patrzeć':'miru', 'patrzę':'miru', 'widzę':'miru', 'widzieć':'miru',
  'czytać':'yomu', 'czytam':'yomu', 'czyta':'yomu', 'czytasz':'yomu', 'przeczytać':'yomu', 'przeczytam':'yomu',
  'pisać':'kaku', 'piszę':'kaku', 'pisze':'kaku', 'piszesz':'kaku', 'napisać':'kaku', 'napisz':'kaku',
  'pracować':'hataraku', 'pracuję':'hataraku', 'pracuje':'hataraku', 'pracujesz':'hataraku',
  'mieszkać':'sumu', 'mieszkam':'sumu', 'mieszka':'sumu',
  'spać':'neru', 'śpię':'neru', 'śpi':'neru', 'spałem':'neru',
  'obudzić':'okiru', 'budzę':'okiru', 'wstaję':'okiru', 'wstać':'okiru',
  'robić':'suru', 'robię':'suru', 'robi':'suru', 'zrobić':'suru', 'zrobię':'suru',
  'biec':'hashiru', 'biegnę':'hashiru', 'biegnie':'hashiru', 'biegać':'hashiru',
  'chodzić':'aruku', 'chodzę':'aruku', 'chodzi':'aruku', 'spacerować':'aruku',
  'dawać':'ageru', 'daję':'ageru', 'daje':'ageru', 'dać':'ageru', 'dam':'ageru',
  'dostawać':'morau', 'dostaję':'morau', 'dostaje':'morau', 'dostać':'morau',
  'szukać':'sagasu', 'szukam':'sagasu', 'szuka':'sagasu',
  'zaczynać':'hajimeru', 'zaczynam':'hajimeru', 'zaczyna':'hajimeru', 'zacząć':'hajimeru', 'zacznę':'hajimeru',
  'uczyć':'benkyou suru', 'uczę':'benkyou suru', 'uczy':'benkyou suru', 'nauczyć':'benkyou suru',
  'śmiać':'warau', 'śmieję':'warau', 'śmieje':'warau', 'roześmiać':'warau',
  'płakać':'naku', 'płaczę':'naku', 'płacze':'naku',
  'śpiewać':'utau', 'śpiewam':'utau', 'śpiewa':'utau',
  'tańczyć':'odoru', 'tańczę':'odoru', 'tańczy':'odoru',
  'bawić':'asobu', 'bawię':'asobu', 'bawi':'asobu',
  // rzeczowniki + odmiany
  'jabłko':'ringo', 'jabłka':'ringo', 'jabłkiem':'ringo', 'jabłku':'ringo',
  'woda':'mizu', 'wodę':'mizu', 'wody':'mizu', 'wodą':'mizu', 'wodzie':'mizu',
  'ryż':'gohan', 'ryżu':'gohan', 'posiłek':'gohan',
  'chleb':'pan', 'chleba':'pan',
  'herbata':'ocha', 'herbatę':'ocha', 'herbaty':'ocha',
  'książka':'hon', 'książkę':'hon', 'książki':'hon', 'książką':'hon',
  'dom':'uchi', 'domu':'uchi', 'domem':'uchi',
  'pokój':'heya', 'pokoju':'heya',
  'szkoła':'gakkou', 'szkoły':'gakkou', 'szkołę':'gakkou', 'szkole':'gakkou',
  'praca':'shigoto', 'pracy':'shigoto', 'pracę':'shigoto',
  'przyjaciel':'tomodachi', 'przyjaciela':'tomodachi', 'przyjacielem':'tomodachi',
  'pieniądze':'okane', 'pieniędzy':'okane',
  'samochód':'kuruma', 'samochodu':'kuruma', 'auto':'kuruma',
  'bohater':'yuusha', 'bohatera':'yuusha', 'bohaterem':'yuusha',
  'lis':'kitsune', 'lisa':'kitsune', 'lisy':'kitsune',
  'magia':'mahou', 'magii':'mahou', 'magię':'mahou', 'czary':'mahou',
  'ogień':'hi', 'ognia':'hi',
  'słońce':'taiyou', 'słońca':'taiyou',
  'księżyc':'tsuki', 'księżyca':'tsuki',
  'niebo':'sora', 'nieba':'sora',
  'morze':'umi', 'morza':'umi', 'morzu':'umi',
  'góra':'yama', 'góry':'yama', 'górę':'yama',
  'drzewo':'ki', 'drzewa':'ki',
  'kwiat':'hana', 'kwiaty':'hana', 'kwiatów':'hana',
  'kot':'neko', 'kota':'neko', 'koty':'neko', 'kotem':'neko',
  // przymiotniki / adverbia
  'nowy':'atarashii', 'nowa':'atarashii', 'nowe':'atarashii',
  'stary':'furui', 'stara':'furui',
  'wysoki':'takai', 'wysoka':'takai', 'drogi':'takai',
  'niski':'hikui', 'niska':'hikui',
  'słodki':'kawaii', 'słodka':'kawaii', 'słodki':'amai',
  'piękny':'kirei', 'piękna':'kirei', 'ładny':'kirei', 'ładna':'kirei',
  'szybko':'hayaku', 'szybki':'hayai',
  'wolno':'yukkuri', 'powoli':'yukkuri',
  'bardzo':'totemo', 'mocno':'totemo',
  'trochę':'sukoshi', 'mało':'sukoshi',
  'codziennie':'mainichi', 'codzienny':'mainichi',
  'teraz':'ima',
  'jutro':'ashita',
  'wczoraj':'kinou',
  'dzisiaj':'kyou', 'dziś':'kyou'
};
const AKEMI_LEGENDS = {
  kitsune: 'W mitologii japońskiej <b>kitsune</b> (狐) to magiczny lis o niezwykłej inteligencji. Im starszy, tym więcej ma ogonów — aż do <b>dziewięciu</b>, co czyni go <b>kyuubi no kitsune</b> (九尾の狐). W świątyniach bóstwa <i>Inari</i> białe figurki kitsune pełnią rolę posłańców. Lisy dzielą się na <b>zenko</b> (dobre) i <b>yako</b> (złośliwe). Najsłynniejszy w popkulturze? Kurama z Naruto lub Holo z Spice and Wolf.',
  tengu: '<b>Tengu</b> (天狗) to górskie duchy wojownicze z Japonii — mieszanki ptaka i człowieka z długim nosem lub dziobem. Według legend są mistrzami sztuk walki i magii wiatru. Słynny miecznik <b>Minamoto no Yoshitsune</b> miał być uczony przez tengu w górach Kurama. W anime widzisz je często w "Demon Slayer" czy "Touhou Project".',
  oni: '<b>Oni</b> (鬼) to japońskie demony — rogate, silne, z żelaznymi maczugami (kanabou). Mimo złowieszczego wyglądu nie zawsze są złe — niektóre są strażnikami lub pokutującymi duszami. <b>Setsubun</b> to święto, podczas którego rzuca się sojowe ziarna krzycząc "Oni wa soto! Fuku wa uchi!" (Demony precz! Szczęście do domu!).',
  samurai: '<b>Samuraj</b> (侍) to wojownicy służący panom feudalnym w okresie od XII do XIX wieku. Ich kodeks honoru to <b>bushido</b> (武士道) — Droga Wojownika. Miecz <b>katana</b> był uznawany za duszę samuraja. Kiedy tracił honor, popełniał <b>seppuku</b> — rytualne samobójstwo. Arcydzieło filmowe o samurajach? "Siedmiu samurajów" Kurosawy.',
  yokai: '<b>Yōkai</b> (妖怪) to ogólny termin na japońskie duchy, demony i nadnaturalne stworzenia. Obejmuje wszystko: kitsune, tengu, kappa, tanuki, yurei... Japoński folklor ma ich setki! Antropolog Shigeru Mizuki narysował encyklopedię yōkai — seria manga "GeGeGe no Kitarō" rozsławiła je na całym świecie.',
  kami: '<b>Kami</b> (神) to duchy/bóstwa shinto — obecne w górach, rzekach, drzewach, kamieniach. Shinto uznaje <b>osiem milionów bogów</b> (<i>yaoyorozu no kami</i>). Największymi są <b>Amaterasu</b> (bogini słońca) i <b>Susanoo</b> (bóg burz). Świątynie <b>jinja</b> poznasz po czerwonej bramie <b>torii</b>.',
  ronin: '<b>Rōnin</b> (浪人) to samuraj bez pana — "człowiek fali". Po śmierci lub upadku swojego daimyō tracił status i źródło utrzymania. Niektórzy zostawali nauczycielami sztuk walki, inni bandytami. Słynni "47 rōninów" dokonali zemsty za śmierć swojego pana, po czym wszyscy popełnili seppuku — to prawdziwa historia z 1703 roku.'
};
const WORLD_REGIONS = [
  { id: 'wioska', name: 'Wioska Początkującego', jp: 'Hajimari no Mura', subtitle: 'Tam gdzie adept stawia pierwsze kroki', icon: '🏘️', color: '#34d399', x: 150, y: 500, requiredPower: 0, categories: ['extra','cz1'], lore: 'Wioska spowita poranną mgłą. Tu młodzi adepci poznają pierwsze runy — partykuły, zaimki, najprostsze zaklęcia bytu. Starsi mówią że nawet najwięksi mistrzowie zaczynali tutaj, pokornie ucząc się rozróżniać WA od GA.' },
  { id: 'las', name: 'Las Partykuł', jp: 'Joshi no Mori', subtitle: 'Mroczny bór gdzie szepczą runy', icon: '🌲', color: '#10b981', x: 380, y: 420, requiredPower: 15, categories: ['extra','nat1','nat2'], lore: 'Las w którym każde drzewo jest wyryte inną runą. Podróżnicy opowiadają że partykuły żyją tu własnym życiem — WO poluje na dopełnienia, NI wskazuje kierunki zagubionym, DE płonie w miejscach gdzie coś się dzieje.' },
  { id: 'rzeka', name: 'Rzeka Czasu', jp: 'Toki no Kawa', subtitle: 'Gdzie przeszłość miesza się z przyszłością', icon: '🌊', color: '#06b6d4', x: 320, y: 560, requiredPower: 25, categories: ['cz1','cz2','cz3'], lore: 'Wielka rzeka której nurt decyduje o formie czasów. Płyniesz z prądem — -mashita (przeszłość), pod prąd — -masu (teraźniejszość, przyszłość). W zakolach kryją się zdradliwe formy -te.' },
  { id: 'gora', name: 'Góra Czasowników', jp: 'Doushi no Yama', subtitle: 'Szczyt na którym mieszkają zaklęcia akcji', icon: '⛰️', color: '#a855f7', x: 620, y: 300, requiredPower: 45, categories: ['cz3','cz4','cz5','cz6'], lore: 'Stroma góra, na której szczycie czasowniki ćwiczą swą odmianę. Grupa pierwsza — dzicy wojownicy. Grupa druga — uczeni mędrcy. Na szczycie stoją dwaj królowie nieregularni: KURU i SURU.' },
  { id: 'miasto', name: 'Miasto Handlu', jp: 'Shijou no Machi', subtitle: 'Zgiełk kupców i codziennej mowy', icon: '🏯', color: '#f5d97a', x: 720, y: 480, requiredPower: 65, categories: ['dom1','dom2','zw1'], lore: 'Tętniące życiem miasto-port. Kupcy targują się po japońsku o rzeczy codzienne — jedzenie, ubrania, dom. Tu dojrzewa język praktyczny, język kantorów i herbaciarni.' },
  { id: 'swiatynia', name: 'Świątynia Yokai', jp: 'Yokai no Jinja', subtitle: 'Gdzie mieszkają duchy anime i isekai', icon: '⛩️', color: '#ec4899', x: 500, y: 150, requiredPower: 90, categories: ['zw2','ani1','ani2'], lore: 'Starożytna świątynia otoczona sakurami. Mieszkają tu stwory z kart twojego mangaka — kitsune machające ogonami, yuusha dzierżący katany, maou knujący intrygi. Tu język spotyka fantazję.' },
  { id: 'palac', name: 'Pałac Mistrzów', jp: 'Shishou no Kyuuden', subtitle: 'Ostateczne arkanum Nihongo', icon: '🏛️', color: '#d4af37', x: 850, y: 200, requiredPower: 130, categories: ['ani2','ani3','extra'], lore: 'Pałac na szczycie wszystkich regionów. Tu mieszkają Mistrzowie którzy dawno zapomnieli że kiedyś mieli problem z różnicą wa/ga. Aby tu wejść, trzeba pokonać wszystkie inne krainy.' }
];
const MAP_PATHS = [['wioska','las'],['wioska','rzeka'],['las','gora'],['las','miasto'],['rzeka','miasto'],['rzeka','swiatynia'],['gora','miasto'],['gora','palac'],['miasto','swiatynia'],['miasto','palac'],['swiatynia','palac']];
const WISDOM_SCROLLS = [
  { id: 1, emoji: '🌸', title: 'Pierwsze Kroki Adepta', titleJp: 'Deshi no Hajimari', region: 'wioska', level: 'N5', minutes: 1,
    content: '[私|watashi|ja] [は|wa|temat] [学生|gakusei|student] [です|desu|jestem].|[アニメ|anime|anime] [を|wo|obiekt] [見ます|mimasu|oglądam].|[日本語|nihongo|japoński] [が|ga|podmiot] [好き|suki|lubiany] [です|desu|jest].',
    translation: 'Jestem studentem. Oglądam anime. Lubię japoński.',
    lore: 'Pierwsza strona dziennika młodego adepta. Prosta, ale zawiera wszystkie trzy partykuły podstawowe — WA, WO, GA. Przeczytaj uważnie, bo te trzy runy tworzą fundament całego Nihongo.' },
  { id: 2, emoji: '🦊', title: 'Kitsune i Wędrowiec', titleJp: 'Kitsune to Tabibito', region: 'las', level: 'N5', minutes: 2,
    content: '[森|mori|las] [に|ni|w] [狐|kitsune|lis] [が|ga|podmiot] [います|imasu|jest].|[狐|kitsune|lis] [は|wa|temat] [賢い|kashikoi|mądry] [です|desu|jest].|[旅人|tabibito|wędrowiec] [は|wa|temat] [狐|kitsune|lis] [に|ni|do] [道|michi|drogę] [を|wo|obiekt] [聞きます|kikimasu|pyta].|[狐|kitsune|lis] [は|wa|temat] [笑います|waraimasu|śmieje się].',
    translation: 'W lesie jest lis. Lis jest mądry. Wędrowiec pyta lisa o drogę. Lis się śmieje.',
    lore: 'Klasyczna historia z japońskiego folkloru. Zauważ jak partykuła NI wskazuje miejsce (w lesie) oraz kierunek akcji (do lisa). To jej dwie twarze.' },
  { id: 3, emoji: '⚔️', title: 'Bohater i Smok', titleJp: 'Yuusha to Ryuu', region: 'swiatynia', level: 'N5', minutes: 2,
    content: '[勇者|yuusha|bohater] [は|wa|temat] [魔王|maou|król demonów] [を|wo|obiekt] [倒します|taoshimasu|pokonuje].|[空|sora|niebo] [に|ni|na] [竜|ryuu|smok] [が|ga|podmiot] [います|imasu|jest].|[竜|ryuu|smok] [は|wa|temat] [強い|tsuyoi|silny] [です|desu|jest].|[勇者|yuusha|bohater] [は|wa|temat] [剣|ken|miecz] [を|wo|obiekt] [持ちます|mochimasu|trzyma].|[戦い|tatakai|walka] [が|ga|podmiot] [始まります|hajimarimasu|rozpoczyna się].',
    translation: 'Bohater pokonuje króla demonów. Na niebie jest smok. Smok jest silny. Bohater trzyma miecz. Rozpoczyna się walka.',
    lore: 'Podstawowy szkielet każdego isekai. Yuusha, maou, ryuu, ken — jeśli znasz te cztery słowa, rozumiesz 80% openingów anime.' },
  { id: 4, emoji: '🍜', title: 'W Ramen-ya', titleJp: 'Ramen-ya de', region: 'miasto', level: 'N5', minutes: 2,
    content: '[店|mise|sklep] [で|de|w] [ラーメン|raamen|ramen] [を|wo|obiekt] [食べます|tabemasu|jem].|[水|mizu|woda] [も|mo|też] [飲みます|nomimasu|piję].|[美味しい|oishii|pyszny] [です|desu|jest].|[店員|tenin|pracownik] [は|wa|temat] [親切|shinsetsu|uprzejmy] [です|desu|jest].|[また|mata|znowu] [来ます|kimasu|przyjdę].',
    translation: 'W lokalu jem ramen. Piję też wodę. Jest pyszne. Pracownik jest uprzejmy. Jeszcze wrócę.',
    lore: 'Partykuła DE oznacza miejsce akcji ("gdzie się coś dzieje"), a MO dodaje znaczenie "też/także". "Mata kimasu" — to fraza którą usłyszysz w każdej herbaciarni.' },
  { id: 5, emoji: '🌙', title: 'Noc Yokai', titleJp: 'Yokai no Yoru', region: 'swiatynia', level: 'N4', minutes: 3,
    content: '[夜|yoru|noc] [が|ga|podmiot] [来ました|kimashita|nadeszła].|[神社|jinja|świątynia] [に|ni|do] [妖怪|yokai|duchy] [が|ga|podmiot] [集まります|atsumarimasu|zbierają się].|[昔|mukashi|dawno], [侍|samurai|samuraj] [が|ga|podmiot] [ここ|koko|tutaj] [で|de|w] [死にました|shinimashita|umarł].|[彼|kare|on] [の|no|posiadanie] [魂|tamashii|dusza] [は|wa|temat] [まだ|mada|wciąż] [ここ|koko|tutaj] [に|ni|w] [います|imasu|jest].|[月|tsuki|księżyc] [を|wo|obiekt] [見て|mite|patrząc], [泣きます|nakimasu|płacze].',
    translation: 'Nadeszła noc. Do świątyni zbierają się duchy. Dawno temu samuraj zginął tutaj. Jego dusza wciąż tu jest. Patrząc na księżyc, płacze.',
    lore: 'Trudniejszy zwój — poziom N4. Zauważ czas przeszły (-mashita), partykułę przynależności NO, oraz formę -te ("mite" = patrząc).' }
];
const HANAMI_LORE = {
  'kitsune': 'Lisica-demon z mitologii. Może mieć do 9 ogonów. Im więcej ogonów, tym większa moc.',
  'yuusha': 'Tytuł nadawany wybrańcom w isekai. Dosłownie "dzielna osoba" — ale niesie ze sobą ciężar ratowania świata.',
  'ryuu': 'Smok. W japońskiej tradycji to istota mądra, związana z wodą i niebem — w przeciwieństwie do złowieszczych smoków zachodnich.',
  'sakura': 'Kwiat wiśni. Symbol ulotności piękna — mono no aware. Kwitnie tylko kilka dni, a potem opada jak śnieg.',
  'tengu': 'Demon górski z długim nosem, dumny i wojowniczy. Niegdyś straszył podróżnych, dziś często pomaga bohaterom.',
  'samurai': 'Wojownik. Słowo pochodzi od "saburau" — służyć. Był sługą pana, wiernym bushido.',
  'neko': 'Kot. W Japonii maneki-neko (machający kot) przynosi szczęście właścicielom sklepów.',
  'inu': 'Pies. Symbol lojalności. W legendzie o Hachikō pies czekał na zmarłego pana przez 9 lat.',
  'watashi': 'Ja — forma grzeczna i uniwersalna. Mężczyźni w nieformalnych sytuacjach użyją "boku" lub "ore".',
  'kami': 'Bóg, duch natury. W shintō każda rzecz może mieć swoją kami — góra, rzeka, stare drzewo.',
  'yokai': 'Kolektywna nazwa na wszystkie nadnaturalne stwory japońskiej mitologii — kitsune, tengu, oni, kappa...',
  'ken': 'Miecz. Ken no michi — "droga miecza" — to ścieżka wojownika i sztuki walki.',
  'hi': 'Ogień. W magii istnieje "hidama" — kula ognia wędrująca nocą po polach.',
  'mizu': 'Woda. Element życia, ale też duchów — wodne yokai jak kappa mieszkają w rzekach.',
  'hana': 'Kwiat. Hanami ("oglądanie kwiatów") to prastary zwyczaj uwielbiania sakury.',
  'tsuki': 'Księżyc. Tsukimi — święto oglądania jesiennego księżyca z dango i sake.',
  'taiyou': 'Słońce. Amaterasu — bogini słońca — to najważniejsze bóstwo w panteonie shintō.',
  'hoshi': 'Gwiazda. W legendzie Tanabata dwie gwiazdy-kochankowie spotykają się raz w roku.',
  'sora': 'Niebo. W isekai "isekai ni ikitai" — "chcę iść do innego świata" — kierują wzrok właśnie tam.',
  'taberu': 'Jeść. Czasownik grupy 2 — łatwa odmiana: tabemasu, tabemashita, tabete.',
  'nomu': 'Pić. Czasownik grupy 1 — nomimasu. Łączy się z mizu (woda), ocha (herbata), sake.',
  'iku': 'Iść. Nieregularna odmiana w formie -te: itte (nie ikite!). Pierwsza pułapka adeptów.',
  'miru': 'Widzieć/oglądać. Anime wo mimasu — oglądam anime. To czasownik codzienny.',
  'wakaru': 'Rozumieć. "Wakarimashita!" — "Zrozumiałem!" — to fraza każdego anime bohatera.',
  'suki': 'Lubiany. "Suki desu" — "Lubię cię". Najbardziej wstydliwe zdanie japońskie.',
  'kawaii': 'Słodki/uroczy. Eksport kulturalny Japonii. Pisane też jako 可愛い.',
  'kakkoii': 'Fajny/cool. Męska wersja "kawaii". Opisuje samurajów, cyborgów, mechy.',
  'genki': 'Zdrowy, pełen energii. "Genki desu ka?" — "Jak się masz?" — standard powitania.',
  'ohayou': 'Dzień dobry (rano). Skrócona forma "ohayou gozaimasu". Używaj do godz. 10-11.',
  'arigatou': 'Dziękuję. "Arigatou gozaimasu" — forma grzeczna. Bez "gozaimasu" — nieformalne.',
  'sumimasen': 'Przepraszam / przepraszam za kłopot. Uniwersalny — używany też zamiast "dziękuję".',
  'isekai': 'Inny świat. Gatunek anime gdzie bohater trafia do innego wymiaru — fantasy lub mroczniejszego świata.',
  'maou': 'Król demonów. Antagonist każdego porządnego isekai. Często okazuje się być "tsundere".',
  'anime': 'Anime. Skrót od angielskiego "animation" adaptowany do japońskiego.',
  'manga': 'Manga. Komiks japoński. Dosłownie "zabawne obrazki" (漫画).'
};
const HANAMI_QUOTES = [
  'Każde słowo jest jak kwiat sakury — piękne, gdy kwitnie, cenne, gdy opadnie.',
  'Adept uczy się tysięcy słów. Mistrz opanowuje jedno dziennie.',
  'Powolne kroki prowadzą dalej niż pośpieszne skoki.',
  'Ten kto każdego dnia odwiedza bibliotekę, odkrywa w niej coraz większe sekrety.',
  'Komorebi — światło przez liście — istnieje tylko gdy zatrzymasz się, by je zauważyć.',
  'Język to ogród. Jedno słowo dziennie — jedno nasiono — i po roku masz gaj.',
  'Kintsugi uczy że pęknięcia to część piękna. Twoje błędy są złotem w twojej nauce.',
  'Dzień w którym nauczyłeś się nowego słowa nie był stracony.'
];
const KIAI_EASY = null; // będą brane z D — pojedyncze słowa
const KIAI_MEDIUM = [
  { jp: 'おはよう ございます', r: 'ohayou gozaimasu', pl: 'Dzień dobry (grzecznie)' },
  { jp: 'ありがとう', r: 'arigatou', pl: 'Dziękuję' },
  { jp: 'すみません', r: 'sumimasen', pl: 'Przepraszam' },
  { jp: 'げんき です か', r: 'genki desu ka', pl: 'Jak się masz?' },
  { jp: 'わかりました', r: 'wakarimashita', pl: 'Zrozumiałem' },
  { jp: 'おねがいします', r: 'onegaishimasu', pl: 'Proszę / proszę bardzo' },
  { jp: 'いただきます', r: 'itadakimasu', pl: 'Zaczynam jeść (dziękuję za posiłek)' },
  { jp: 'よろしく', r: 'yoroshiku', pl: 'Miło mi cię poznać / proszę o życzliwość' },
  { jp: 'また ね', r: 'mata ne', pl: 'Do zobaczenia' },
  { jp: 'だいじょうぶ', r: 'daijoubu', pl: 'W porządku / nic się nie stało' },
  { jp: 'すき です', r: 'suki desu', pl: 'Lubię to' },
  { jp: 'きれい です', r: 'kirei desu', pl: 'Jest piękny' }
];
const KIAI_HARD = [
  { jp: 'わたし は がくせい です', r: 'watashi wa gakusei desu', pl: 'Jestem studentem' },
  { jp: 'りんご を たべます', r: 'ringo wo tabemasu', pl: 'Jem jabłko' },
  { jp: 'にほんご が すき です', r: 'nihongo ga suki desu', pl: 'Lubię japoński' },
  { jp: 'アニメ を みます', r: 'anime wo mimasu', pl: 'Oglądam anime' },
  { jp: 'わたし は いきたい です', r: 'watashi wa ikitai desu', pl: 'Chcę iść' },
  { jp: 'もり に きつね が います', r: 'mori ni kitsune ga imasu', pl: 'W lesie jest lis' },
  { jp: 'ゆうしゃ は つよい です', r: 'yuusha wa tsuyoi desu', pl: 'Bohater jest silny' },
  { jp: 'みず を のみます', r: 'mizu wo nomimasu', pl: 'Piję wodę' },
  { jp: 'ほん を よみます', r: 'hon wo yomimasu', pl: 'Czytam książkę' },
  { jp: 'がっこう に いきます', r: 'gakkou ni ikimasu', pl: 'Idę do szkoły' }
];
const SCENES = [
  {
    id: 'ramen',
    emoji: '🍜',
    color: '#f5d97a',
    title: 'W Ramen-ya',
    titleJp: 'Ramen-ya de',
    character: 'Pani Akemi (kelnerka)',
    characterEmoji: '👩‍🍳',
    place: 'Mała knajpka z ramen na bocznej uliczce Tokio. Para unosi się znad miski tonkotsu. Słychać dzwonek nad drzwiami.',
    level: 'N5',
    duration: '5-10 min',
    keyVocab: ['ramen', 'mizu', 'oishii', 'itadakimasu', 'okaikei', 'arigatou'],
    description: 'Wchodzisz do ramen-ya po długim dniu. Kelnerka wita cię z uśmiechem, wręcza menu i czeka na zamówienie.',
    systemPrompt: `Jesteś kelnerką (店員 ten'in) w małej, tradycyjnej ramen-ya w Tokio. Adept (gracz) właśnie wszedł.
TWOJA POSTAĆ: Uprzejma, ciepła, używa keigo (formy grzecznej -masu). Pomagasz adeptowi z japońskim. Jeśli adept napisze coś po polsku — odpowiadasz po japońsku z tłumaczeniem polskim. Jeśli pisze po japońsku — odpowiadasz głównie po japońsku, koniecznie z tłumaczeniem polskim.
WAŻNE:
- Trzymaj się sytuacji: zamówienie, podanie wody, dostarczenie ramen, płatność, pożegnanie.
- Używaj prostych słów N5: ramen, mizu, oishii, itadakimasu, okaikei (rachunek), arigatou.
- Odpowiadaj KRÓTKO (1-3 zdania).
- ZAWSZE używaj JSON z polami: "action" (krótki opis akcji w *gwiazdkach* po polsku, np. "Uśmiecha się i kłania"), "jp" (po japońsku, hiragana/katakana/kanji), "romaji" (transkrypcja romaji), "translation" (tłumaczenie polskie), "suggestions" (tablica 2-3 propozycji odpowiedzi adepta — każda jako obiekt {jp, romaji, pl}).
- Jeśli adept zrobi błąd gramatyczny lub użyje niepoprawnego słowa — łagodnie napraw: powtórz poprawnie i krótko wyjaśnij.
- Po 5-7 wymianach przejdź do zakończenia (płatność, pożegnanie).`
  },
  {
    id: 'kupiec',
    emoji: '🏪',
    color: '#10b981',
    title: 'U Kupca',
    titleJp: 'Shouten de',
    character: 'Stary Kupiec',
    characterEmoji: '🧔',
    place: 'Wąski sklepik w bocznej uliczce miasta. Półki uginają się pod owocami, eliksirami i artefaktami z dalekich krain. Stary kupiec o przenikliwym spojrzeniu pochyla się nad ladą.',
    level: 'N5',
    duration: '5-10 min',
    keyVocab: ['kau', 'ringo', 'mizu', 'kagi', 'ikura', 'takai', 'yasui'],
    description: 'Wchodzisz do sklepiku awanturnika. Możesz kupić jedzenie, klucze, eliksiry. Pora się targować!',
    systemPrompt: `Jesteś starym, przebiegłym kupcem (商人 shounin) w średniowiecznym fantasy mieście. Adept właśnie wszedł.
TWOJA POSTAĆ: Mówisz nieco zachęcająco-handlowo, czasem żartujesz, ale uczciwie. Sprzedajesz: ringo (jabłka, 100 yen), mizu (woda, 50 yen), kagi (klucze, 500 yen), pan (chleb, 200 yen), kusuri (lekarstwa, 800 yen). Lubisz gdy ktoś się targuje.
WAŻNE:
- Używaj prostych słów N5: ikura desu ka? (ile kosztuje?), takai (drogi), yasui (tani), kau (kupować).
- Jeśli adept napisze po polsku — odpowiadasz po japońsku z tłumaczeniem.
- Krótkie odpowiedzi (1-3 zdania).
- ZAWSZE JSON: action (po polsku w *gwiazdkach*), jp, romaji, translation, suggestions (2-3 propozycje {jp, romaji, pl}).
- Po 5-7 wymianach finalizuj transakcję i pożegnaj.`
  },
  {
    id: 'gildia',
    emoji: '🏛️',
    color: '#a855f7',
    title: 'W Gildii Awanturników',
    titleJp: 'Bouken-sha Girudo de',
    character: 'Receptionistka Yuki',
    characterEmoji: '🧝‍♀️',
    place: 'Wielki hol gildii pełen wojowników, magów i awanturników. Tablica misji wisi na ścianie. Recepcjonistka Yuki uśmiecha się zza lady.',
    level: 'N4',
    duration: '5-10 min',
    keyVocab: ['misshon', 'monsuta', 'reberu', 'soubi', 'nakama', 'tatakai'],
    description: 'Twoja pierwsza wizyta w gildii awanturników. Yuki pomoże zarejestrować się i wybrać pierwszą misję.',
    systemPrompt: `Jesteś Yuki, młodą elfką-recepcjonistką w gildii awanturników (冒険者ギルド). Adept (gracz) właśnie wszedł — to jego pierwsza wizyta.
TWOJA POSTAĆ: Energiczna, profesjonalna, mówi tonem ciepło-służbowym. Pomagasz wybrać misję, sprawdzić poziom (reberu), ekwipunek (soubi). Mówisz też o nakama (drużynie).
WAŻNE:
- Używaj słów isekai: misshon, monsuta, reberu, soubi, nakama, tatakai, kaifuku, doku.
- Proponowane misje: 1) Pokonaj 5 monsuta w lesie (poziom 1, 100 keiken), 2) Znajdź zaginiony kagi w jaskini (poziom 2, 200 keiken), 3) Eskortuj kupca do miasta (poziom 1, 150 keiken).
- Jeśli po polsku — odpowiadasz po japońsku z tłumaczeniem.
- Krótkie odpowiedzi (1-3 zdania).
- ZAWSZE JSON: action (po polsku w *gwiazdkach*), jp, romaji, translation, suggestions (2-3 {jp, romaji, pl}).
- Po wyborze misji życzysz powodzenia i kończysz.`
  },
  {
    id: 'swiatynia',
    emoji: '⛩️',
    color: '#ec4899',
    title: 'W Świątyni Yokai',
    titleJp: 'Yokai no Jinja de',
    character: 'Kapłanka Sayuri',
    characterEmoji: '🙇‍♀️',
    place: 'Stara świątynia ukryta w bambusowym lesie. Zapach kadzideł. Przy ołtarzu stoi cicha kapłanka w białej kimono. Słychać dzwonek wiatru.',
    level: 'N4',
    duration: '5-10 min',
    keyVocab: ['kami', 'inori', 'unmei', 'kibou', 'tamashii', 'mahou'],
    description: 'Przybywasz do tajemniczej świątyni. Kapłanka czuje twoją obecność i odwraca głowę. Może odsłoni ci sekret twojego przeznaczenia?',
    systemPrompt: `Jesteś Sayuri, młodą kapłanką (巫女 miko) w starożytnej świątyni shinto ukrytej w bambusowym lesie. Adept (gracz) właśnie wszedł.
TWOJA POSTAĆ: Spokojna, tajemnicza, mądra. Mówisz w klimacie isekai/duchowym. Czytasz przeznaczenie z talii kart, opowiadasz o kami i yokai. Pytasz adepta o jego cel, nadzieję, lęk.
WAŻNE:
- Używaj słów: kami (bóg), inori (modlitwa), unmei (przeznaczenie), kibou (nadzieja), tamashii (dusza), mahou (magia), yurei (duchy).
- Jeśli po polsku — odpowiadasz po japońsku z tłumaczeniem.
- Krótkie, ale poetyckie odpowiedzi (2-3 zdania).
- ZAWSZE JSON: action (po polsku w *gwiazdkach*), jp, romaji, translation, suggestions (2-3 {jp, romaji, pl}).
- Po 5-7 wymianach daj adeptowi przepowiednię/błogosławieństwo i zakończ.`
  },
  {
    id: 'isekai',
    emoji: '✨',
    color: '#06b6d4',
    title: 'Przybycie do Isekai',
    titleJp: 'Isekai e Tousha',
    character: 'Bogini Megami',
    characterEmoji: '👼',
    place: 'Bezkresna biała przestrzeń. Lewitujesz w pustce. Przed tobą piękna bogini o złotych oczach uśmiecha się łagodnie. To moment przed transmigracją.',
    level: 'N4',
    duration: '5-10 min',
    keyVocab: ['tensei', 'isekai', 'mahou', 'yuusha', 'sukiru', 'unmei'],
    description: 'Umarłeś. Ale to nie koniec — bogini oferuje ci nowe życie w innym świecie. Możesz wybrać klasę, umiejętności, imię. Klasyczne otwarcie isekai!',
    systemPrompt: `Jesteś Megami (女神 bogini), boską istotą która oferuje adeptowi reinkarnację (転生 tensei) do isekai. Adept właśnie umarł i przybył do twojego białego pokoju.
TWOJA POSTAĆ: Ciepła, łagodna, ale mądra. Wyjaśniasz że adept dostanie nowe życie w fantasy świecie. Pytasz o wybór klasy (mahou tsukai/yuusha/senshi), umiejętność (mahou ognia/leczenie/super siła), imię w nowym świecie. Tłumaczysz co robić w isekai.
WAŻNE:
- Używaj słów: tensei, isekai, mahou, yuusha, sukiru, unmei, sekai, maou (do pokonania).
- Jeśli po polsku — odpowiadasz po japońsku z tłumaczeniem.
- Krótkie, magiczne odpowiedzi (2-3 zdania).
- ZAWSZE JSON: action (po polsku w *gwiazdkach*), jp, romaji, translation, suggestions (2-3 {jp, romaji, pl}).
- Po wyborze klasy, umiejętności i imienia — pożegnaj się i wyślij adepta do nowego świata.`
  }
];
const SRS_STATE_KEY = 'arcana_srs_state';
const SRS_ACTIVITY_KEY = 'arcana_srs_activity'; // dzienne liczniki nauki
const RAG_SERVER_URL = 'http://localhost:5000/chat';
const USE_LOCAL_FALLBACK = true;
